// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Advanced  extends Abstract_declarator {
  public final Dir_abs_dec dir_abs_dec_;
  public Advanced(Dir_abs_dec p1) { dir_abs_dec_ = p1; }

  public <R,A> R accept(c.Absyn.Abstract_declarator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Advanced) {
      c.Absyn.Advanced x = (c.Absyn.Advanced)o;
      return this.dir_abs_dec_.equals(x.dir_abs_dec_);
    }
    return false;
  }

  public int hashCode() {
    return this.dir_abs_dec_.hashCode();
  }


}
