// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Declarator implements java.io.Serializable {
  public abstract <R,A> R accept(Declarator.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.BeginPointer p, A arg);
    public R visit(c.Absyn.NoPointer p, A arg);

  }

}
