// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Echar  extends Constant {
  public final Character char_;
  public Echar(Character p1) { char_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Echar) {
      c.Absyn.Echar x = (c.Absyn.Echar)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
