// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

import c.InternalTypeRepresentation;

public class Econdition  extends Exp {
  public final Exp exp_1, exp_2, exp_3;
  public Econdition(Exp p1, Exp p2, Exp p3) { exp_1 = p1; exp_2 = p2; exp_3 = p3; }

  public <R,A> R accept(c.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Econdition) {
      c.Absyn.Econdition x = (c.Absyn.Econdition)o;
      return this.exp_1.equals(x.exp_1) && this.exp_2.equals(x.exp_2) && this.exp_3.equals(x.exp_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_1.hashCode())+this.exp_2.hashCode())+this.exp_3.hashCode();
  }


}
