// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Efloat  extends Constant {
  public final Double double_;
  public Efloat(Double p1) { double_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Efloat) {
      c.Absyn.Efloat x = (c.Absyn.Efloat)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
