// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class EnumName  extends Enum_specifier {
  public final String ident_;
  public final ListEnumerator listenumerator_;
  public EnumName(String p1, ListEnumerator p2) { ident_ = p1; listenumerator_ = p2; }

  public <R,A> R accept(c.Absyn.Enum_specifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.EnumName) {
      c.Absyn.EnumName x = (c.Absyn.EnumName)o;
      return this.ident_.equals(x.ident_) && this.listenumerator_.equals(x.listenumerator_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listenumerator_.hashCode();
  }


}
