// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Enumerator implements java.io.Serializable {
  public abstract <R,A> R accept(Enumerator.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Plain p, A arg);
    public R visit(c.Absyn.EnumInit p, A arg);

  }

}
