// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class EnumVar  extends Enum_specifier {
  public final String ident_;
  public EnumVar(String p1) { ident_ = p1; }

  public <R,A> R accept(c.Absyn.Enum_specifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.EnumVar) {
      c.Absyn.EnumVar x = (c.Absyn.EnumVar)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
