// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Eoctallong  extends Constant {
  public final String octallong_;
  public Eoctallong(String p1) { octallong_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Eoctallong) {
      c.Absyn.Eoctallong x = (c.Absyn.Eoctallong)o;
      return this.octallong_.equals(x.octallong_);
    }
    return false;
  }

  public int hashCode() {
    return this.octallong_.hashCode();
  }


}
