// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Eselect  extends Exp {
  public final Exp exp_;
  public final String ident_;
  public Eselect(Exp p1, String p2) { exp_ = p1; ident_ = p2; }

  public <R,A> R accept(c.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Eselect) {
      c.Absyn.Eselect x = (c.Absyn.Eselect)o;
      return this.exp_.equals(x.exp_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.ident_.hashCode();
  }


}
