// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Especial  extends Constant_expression {
  public final Exp exp_;
  public Especial(Exp p1) { exp_ = p1; }

  public <R,A> R accept(c.Absyn.Constant_expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Especial) {
      c.Absyn.Especial x = (c.Absyn.Especial)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
