// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Eunsignlong  extends Constant {
  public final String unsignedlong_;
  public Eunsignlong(String p1) { unsignedlong_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Eunsignlong) {
      c.Absyn.Eunsignlong x = (c.Absyn.Eunsignlong)o;
      return this.unsignedlong_.equals(x.unsignedlong_);
    }
    return false;
  }

  public int hashCode() {
    return this.unsignedlong_.hashCode();
  }


}
