// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class InitListTwo  extends Initializer {
  public final Initializers initializers_;
  public InitListTwo(Initializers p1) { initializers_ = p1; }

  public <R,A> R accept(c.Absyn.Initializer.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.InitListTwo) {
      c.Absyn.InitListTwo x = (c.Absyn.InitListTwo)o;
      return this.initializers_.equals(x.initializers_);
    }
    return false;
  }

  public int hashCode() {
    return this.initializers_.hashCode();
  }


}
