// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Jump_stm implements java.io.Serializable {
  public abstract <R,A> R accept(Jump_stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.SjumpOne p, A arg);
    public R visit(c.Absyn.SjumpTwo p, A arg);
    public R visit(c.Absyn.SjumpThree p, A arg);
    public R visit(c.Absyn.SjumpFour p, A arg);
    public R visit(c.Absyn.SjumpFive p, A arg);

  }

}
