// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class LocalProgram  extends Storage_class_specifier {
  public LocalProgram() { }

  public <R,A> R accept(c.Absyn.Storage_class_specifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.LocalProgram) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
