// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class MoreInit  extends Initializers {
  public final Initializers initializers_;
  public final Initializer initializer_;
  public MoreInit(Initializers p1, Initializer p2) { initializers_ = p1; initializer_ = p2; }

  public <R,A> R accept(c.Absyn.Initializers.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.MoreInit) {
      c.Absyn.MoreInit x = (c.Absyn.MoreInit)o;
      return this.initializers_.equals(x.initializers_) && this.initializer_.equals(x.initializer_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.initializers_.hashCode())+this.initializer_.hashCode();
  }


}
