// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class More  extends Parameter_type {
  public final Parameter_declarations parameter_declarations_;
  public More(Parameter_declarations p1) { parameter_declarations_ = p1; }

  public <R,A> R accept(c.Absyn.Parameter_type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.More) {
      c.Absyn.More x = (c.Absyn.More)o;
      return this.parameter_declarations_.equals(x.parameter_declarations_);
    }
    return false;
  }

  public int hashCode() {
    return this.parameter_declarations_.hashCode();
  }


}
