// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class NewFuncExpr  extends Dir_abs_dec {
  public final Dir_abs_dec dir_abs_dec_;
  public final Parameter_type parameter_type_;
  public NewFuncExpr(Dir_abs_dec p1, Parameter_type p2) { dir_abs_dec_ = p1; parameter_type_ = p2; }

  public <R,A> R accept(c.Absyn.Dir_abs_dec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.NewFuncExpr) {
      c.Absyn.NewFuncExpr x = (c.Absyn.NewFuncExpr)o;
      return this.dir_abs_dec_.equals(x.dir_abs_dec_) && this.parameter_type_.equals(x.parameter_type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.dir_abs_dec_.hashCode())+this.parameter_type_.hashCode();
  }


}
