// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class NewFunc  extends Function_def {
  public final ListDeclaration_specifier listdeclaration_specifier_;
  public final Declarator declarator_;
  public final Compound_stm compound_stm_;
  public NewFunc(ListDeclaration_specifier p1, Declarator p2, Compound_stm p3) { listdeclaration_specifier_ = p1; declarator_ = p2; compound_stm_ = p3; }

  public <R,A> R accept(c.Absyn.Function_def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.NewFunc) {
      c.Absyn.NewFunc x = (c.Absyn.NewFunc)o;
      return this.listdeclaration_specifier_.equals(x.listdeclaration_specifier_) && this.declarator_.equals(x.declarator_) && this.compound_stm_.equals(x.compound_stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.listdeclaration_specifier_.hashCode())+this.declarator_.hashCode())+this.compound_stm_.hashCode();
  }


}
