// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class OldFuncInt  extends Function_def {
  public final Declarator declarator_;
  public final ListDec listdec_;
  public final Compound_stm compound_stm_;
  public OldFuncInt(Declarator p1, ListDec p2, Compound_stm p3) { declarator_ = p1; listdec_ = p2; compound_stm_ = p3; }

  public <R,A> R accept(c.Absyn.Function_def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.OldFuncInt) {
      c.Absyn.OldFuncInt x = (c.Absyn.OldFuncInt)o;
      return this.declarator_.equals(x.declarator_) && this.listdec_.equals(x.listdec_) && this.compound_stm_.equals(x.compound_stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.declarator_.hashCode())+this.listdec_.hashCode())+this.compound_stm_.hashCode();
  }


}
