// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class OldFunction  extends Dir_abs_dec {
  public OldFunction() { }

  public <R,A> R accept(c.Absyn.Dir_abs_dec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.OldFunction) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
