// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class OldFuncDef  extends Direct_declarator {
  public final Direct_declarator direct_declarator_;
  public final ListIdent listident_;
  public OldFuncDef(Direct_declarator p1, ListIdent p2) { direct_declarator_ = p1; listident_ = p2; }

  public <R,A> R accept(c.Absyn.Direct_declarator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.OldFuncDef) {
      c.Absyn.OldFuncDef x = (c.Absyn.OldFuncDef)o;
      return this.direct_declarator_.equals(x.direct_declarator_) && this.listident_.equals(x.listident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.direct_declarator_.hashCode())+this.listident_.hashCode();
  }


}
