// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class OnlyType  extends Parameter_declaration {
  public final ListDeclaration_specifier listdeclaration_specifier_;
  public OnlyType(ListDeclaration_specifier p1) { listdeclaration_specifier_ = p1; }

  public <R,A> R accept(c.Absyn.Parameter_declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.OnlyType) {
      c.Absyn.OnlyType x = (c.Absyn.OnlyType)o;
      return this.listdeclaration_specifier_.equals(x.listdeclaration_specifier_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdeclaration_specifier_.hashCode();
  }


}
