// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class OnlyDecl  extends Init_declarator {
  public final Declarator declarator_;
  public OnlyDecl(Declarator p1) { declarator_ = p1; }

  public <R,A> R accept(c.Absyn.Init_declarator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.OnlyDecl) {
      c.Absyn.OnlyDecl x = (c.Absyn.OnlyDecl)o;
      return this.declarator_.equals(x.declarator_);
    }
    return false;
  }

  public int hashCode() {
    return this.declarator_.hashCode();
  }


}
