// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class PointAdvanced  extends Abstract_declarator {
  public final Pointer pointer_;
  public final Dir_abs_dec dir_abs_dec_;
  public PointAdvanced(Pointer p1, Dir_abs_dec p2) { pointer_ = p1; dir_abs_dec_ = p2; }

  public <R,A> R accept(c.Absyn.Abstract_declarator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.PointAdvanced) {
      c.Absyn.PointAdvanced x = (c.Absyn.PointAdvanced)o;
      return this.pointer_.equals(x.pointer_) && this.dir_abs_dec_.equals(x.dir_abs_dec_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pointer_.hashCode())+this.dir_abs_dec_.hashCode();
  }


}
