// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Pointer implements java.io.Serializable {
  public abstract <R,A> R accept(Pointer.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Point p, A arg);
    public R visit(c.Absyn.PointQual p, A arg);
    public R visit(c.Absyn.PointPoint p, A arg);
    public R visit(c.Absyn.PointQualPoint p, A arg);

  }

}
