// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Progr  extends Program {
  public final ListExternal_declaration listexternal_declaration_;
  public Progr(ListExternal_declaration p1) { listexternal_declaration_ = p1; }

  public <R,A> R accept(c.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Progr) {
      c.Absyn.Progr x = (c.Absyn.Progr)o;
      return this.listexternal_declaration_.equals(x.listexternal_declaration_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexternal_declaration_.hashCode();
  }


}
