// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class ScompFour  extends Compound_stm {
  public final ListDec listdec_;
  public final ListStm liststm_;
  public ScompFour(ListDec p1, ListStm p2) { listdec_ = p1; liststm_ = p2; }

  public <R,A> R accept(c.Absyn.Compound_stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.ScompFour) {
      c.Absyn.ScompFour x = (c.Absyn.ScompFour)o;
      return this.listdec_.equals(x.listdec_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listdec_.hashCode())+this.liststm_.hashCode();
  }


}
