// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class SexprTwo  extends Expression_stm {
  public final Exp exp_;
  public SexprTwo(Exp p1) { exp_ = p1; }

  public <R,A> R accept(c.Absyn.Expression_stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.SexprTwo) {
      c.Absyn.SexprTwo x = (c.Absyn.SexprTwo)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
