// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class SlabelThree  extends Labeled_stm {
  public final Stm stm_;
  public SlabelThree(Stm p1) { stm_ = p1; }

  public <R,A> R accept(c.Absyn.Labeled_stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.SlabelThree) {
      c.Absyn.SlabelThree x = (c.Absyn.SlabelThree)o;
      return this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_.hashCode();
  }


}
