// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class SselTwo  extends Selection_stm {
  public final Exp exp_;
  public final Stm stm_1, stm_2;
  public SselTwo(Exp p1, Stm p2, Stm p3) { exp_ = p1; stm_1 = p2; stm_2 = p3; }

  public <R,A> R accept(c.Absyn.Selection_stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.SselTwo) {
      c.Absyn.SselTwo x = (c.Absyn.SselTwo)o;
      return this.exp_.equals(x.exp_) && this.stm_1.equals(x.stm_1) && this.stm_2.equals(x.stm_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_.hashCode())+this.stm_1.hashCode())+this.stm_2.hashCode();
  }


}
