// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Struct_or_union implements java.io.Serializable {
  public abstract <R,A> R accept(Struct_or_union.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Struct p, A arg);
    public R visit(c.Absyn.Union p, A arg);

  }

}
