// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class TagType  extends Struct_or_union_spec {
  public final Struct_or_union struct_or_union_;
  public final String ident_;
  public TagType(Struct_or_union p1, String p2) { struct_or_union_ = p1; ident_ = p2; }

  public <R,A> R accept(c.Absyn.Struct_or_union_spec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.TagType) {
      c.Absyn.TagType x = (c.Absyn.TagType)o;
      return this.struct_or_union_.equals(x.struct_or_union_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.struct_or_union_.hashCode())+this.ident_.hashCode();
  }


}
