// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Type_specifier implements java.io.Serializable {
  public abstract <R,A> R accept(Type_specifier.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Tvoid p, A arg);
    public R visit(c.Absyn.Tchar p, A arg);
    public R visit(c.Absyn.Tshort p, A arg);
    public R visit(c.Absyn.Tint p, A arg);
    public R visit(c.Absyn.Tlong p, A arg);
    public R visit(c.Absyn.Tfloat p, A arg);
    public R visit(c.Absyn.Tdouble p, A arg);
    public R visit(c.Absyn.Tsigned p, A arg);
    public R visit(c.Absyn.Tunsigned p, A arg);
    public R visit(c.Absyn.Tstruct p, A arg);
    public R visit(c.Absyn.Tenum p, A arg);
    public R visit(c.Absyn.Tname p, A arg);

  }

}
