// -*- Java -*- File generated by the BNF Converter (bnfc 2.9.5).
// Lexer definition for use with JLex
package c;
import java_cup.runtime.SymbolFactory;
import java_cup.runtime.ComplexSymbolFactory;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  final int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yyline = unknown - 1;
  int yycolumn = unknown - 1;
  int yychar = unknown;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return left;
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return left;
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		159,
		161,
		163,
		165,
		167,
		169
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NOT_ACCEPT,
		/* 132 */ YY_NO_ANCHOR,
		/* 133 */ YY_NO_ANCHOR,
		/* 134 */ YY_NO_ANCHOR,
		/* 135 */ YY_NO_ANCHOR,
		/* 136 */ YY_NO_ANCHOR,
		/* 137 */ YY_NO_ANCHOR,
		/* 138 */ YY_NO_ANCHOR,
		/* 139 */ YY_NO_ANCHOR,
		/* 140 */ YY_NO_ANCHOR,
		/* 141 */ YY_NO_ANCHOR,
		/* 142 */ YY_NO_ANCHOR,
		/* 143 */ YY_NO_ANCHOR,
		/* 144 */ YY_NO_ANCHOR,
		/* 145 */ YY_NO_ANCHOR,
		/* 146 */ YY_NOT_ACCEPT,
		/* 147 */ YY_NO_ANCHOR,
		/* 148 */ YY_NO_ANCHOR,
		/* 149 */ YY_NOT_ACCEPT,
		/* 150 */ YY_NO_ANCHOR,
		/* 151 */ YY_NOT_ACCEPT,
		/* 152 */ YY_NO_ANCHOR,
		/* 153 */ YY_NOT_ACCEPT,
		/* 154 */ YY_NO_ANCHOR,
		/* 155 */ YY_NOT_ACCEPT,
		/* 156 */ YY_NO_ANCHOR,
		/* 157 */ YY_NOT_ACCEPT,
		/* 158 */ YY_NO_ANCHOR,
		/* 159 */ YY_NOT_ACCEPT,
		/* 160 */ YY_NO_ANCHOR,
		/* 161 */ YY_NOT_ACCEPT,
		/* 162 */ YY_NO_ANCHOR,
		/* 163 */ YY_NOT_ACCEPT,
		/* 164 */ YY_NO_ANCHOR,
		/* 165 */ YY_NOT_ACCEPT,
		/* 166 */ YY_NO_ANCHOR,
		/* 167 */ YY_NOT_ACCEPT,
		/* 168 */ YY_NO_ANCHOR,
		/* 169 */ YY_NOT_ACCEPT,
		/* 170 */ YY_NO_ANCHOR,
		/* 171 */ YY_NO_ANCHOR,
		/* 172 */ YY_NO_ANCHOR,
		/* 173 */ YY_NO_ANCHOR,
		/* 174 */ YY_NO_ANCHOR,
		/* 175 */ YY_NO_ANCHOR,
		/* 176 */ YY_NO_ANCHOR,
		/* 177 */ YY_NO_ANCHOR,
		/* 178 */ YY_NO_ANCHOR,
		/* 179 */ YY_NO_ANCHOR,
		/* 180 */ YY_NO_ANCHOR,
		/* 181 */ YY_NO_ANCHOR,
		/* 182 */ YY_NO_ANCHOR,
		/* 183 */ YY_NO_ANCHOR,
		/* 184 */ YY_NO_ANCHOR,
		/* 185 */ YY_NO_ANCHOR,
		/* 186 */ YY_NO_ANCHOR,
		/* 187 */ YY_NO_ANCHOR,
		/* 188 */ YY_NO_ANCHOR,
		/* 189 */ YY_NO_ANCHOR,
		/* 190 */ YY_NO_ANCHOR,
		/* 191 */ YY_NO_ANCHOR,
		/* 192 */ YY_NO_ANCHOR,
		/* 193 */ YY_NO_ANCHOR,
		/* 194 */ YY_NO_ANCHOR,
		/* 195 */ YY_NO_ANCHOR,
		/* 196 */ YY_NO_ANCHOR,
		/* 197 */ YY_NO_ANCHOR,
		/* 198 */ YY_NO_ANCHOR,
		/* 199 */ YY_NO_ANCHOR,
		/* 200 */ YY_NO_ANCHOR,
		/* 201 */ YY_NO_ANCHOR,
		/* 202 */ YY_NO_ANCHOR,
		/* 203 */ YY_NO_ANCHOR,
		/* 204 */ YY_NO_ANCHOR,
		/* 205 */ YY_NO_ANCHOR,
		/* 206 */ YY_NO_ANCHOR,
		/* 207 */ YY_NO_ANCHOR,
		/* 208 */ YY_NO_ANCHOR,
		/* 209 */ YY_NO_ANCHOR,
		/* 210 */ YY_NO_ANCHOR,
		/* 211 */ YY_NO_ANCHOR,
		/* 212 */ YY_NO_ANCHOR,
		/* 213 */ YY_NO_ANCHOR,
		/* 214 */ YY_NO_ANCHOR,
		/* 215 */ YY_NO_ANCHOR,
		/* 216 */ YY_NO_ANCHOR,
		/* 217 */ YY_NO_ANCHOR,
		/* 218 */ YY_NO_ANCHOR,
		/* 219 */ YY_NO_ANCHOR,
		/* 220 */ YY_NO_ANCHOR,
		/* 221 */ YY_NO_ANCHOR,
		/* 222 */ YY_NO_ANCHOR,
		/* 223 */ YY_NO_ANCHOR,
		/* 224 */ YY_NO_ANCHOR,
		/* 225 */ YY_NO_ANCHOR,
		/* 226 */ YY_NO_ANCHOR,
		/* 227 */ YY_NO_ANCHOR,
		/* 228 */ YY_NO_ANCHOR,
		/* 229 */ YY_NO_ANCHOR,
		/* 230 */ YY_NO_ANCHOR,
		/* 231 */ YY_NO_ANCHOR,
		/* 232 */ YY_NO_ANCHOR,
		/* 233 */ YY_NO_ANCHOR,
		/* 234 */ YY_NO_ANCHOR,
		/* 235 */ YY_NO_ANCHOR,
		/* 236 */ YY_NO_ANCHOR,
		/* 237 */ YY_NO_ANCHOR,
		/* 238 */ YY_NO_ANCHOR,
		/* 239 */ YY_NO_ANCHOR,
		/* 240 */ YY_NO_ANCHOR,
		/* 241 */ YY_NO_ANCHOR,
		/* 242 */ YY_NO_ANCHOR,
		/* 243 */ YY_NO_ANCHOR,
		/* 244 */ YY_NO_ANCHOR,
		/* 245 */ YY_NO_ANCHOR,
		/* 246 */ YY_NO_ANCHOR,
		/* 247 */ YY_NO_ANCHOR,
		/* 248 */ YY_NO_ANCHOR,
		/* 249 */ YY_NO_ANCHOR,
		/* 250 */ YY_NO_ANCHOR,
		/* 251 */ YY_NO_ANCHOR,
		/* 252 */ YY_NO_ANCHOR,
		/* 253 */ YY_NO_ANCHOR,
		/* 254 */ YY_NO_ANCHOR,
		/* 255 */ YY_NO_ANCHOR,
		/* 256 */ YY_NO_ANCHOR,
		/* 257 */ YY_NO_ANCHOR,
		/* 258 */ YY_NO_ANCHOR,
		/* 259 */ YY_NO_ANCHOR,
		/* 260 */ YY_NO_ANCHOR,
		/* 261 */ YY_NO_ANCHOR,
		/* 262 */ YY_NO_ANCHOR,
		/* 263 */ YY_NO_ANCHOR,
		/* 264 */ YY_NO_ANCHOR,
		/* 265 */ YY_NO_ANCHOR,
		/* 266 */ YY_NO_ANCHOR,
		/* 267 */ YY_NO_ANCHOR,
		/* 268 */ YY_NO_ANCHOR,
		/* 269 */ YY_NO_ANCHOR,
		/* 270 */ YY_NO_ANCHOR,
		/* 271 */ YY_NO_ANCHOR,
		/* 272 */ YY_NO_ANCHOR,
		/* 273 */ YY_NO_ANCHOR,
		/* 274 */ YY_NO_ANCHOR,
		/* 275 */ YY_NO_ANCHOR,
		/* 276 */ YY_NO_ANCHOR,
		/* 277 */ YY_NO_ANCHOR,
		/* 278 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"53:9,69,54,53,69,51,53:18,69,17,64,52,53,23,15,66,7,8,11,20,2,21,12,22,56,6" +
"1:7,55:2,6,1,18,3,19,13,53,60:4,62,63,67:5,58,67:7,25,57,67:2,59,67:2,9,65," +
"10,16,31,53,33,38,41,29,28,30,47,43,44,68,40,45,34,32,37,27,68,39,42,36,35," +
"50,49,46,26,48,4,14,5,24,53:65,67:23,53,67:7,68:24,53,68:8,53:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,279,
"0,1:3,2,1:7,3,4,1,5,6,7,8,9,10,11,12,13,14,1,15,1:2,16,17,18,1:4,19,1:7,20," +
"1,21,1:7,22,1,23,24,25,1,26,1:6,24:2,27,1:2,28,24:8,29,1,24:6,1,24:15,1:11," +
"30,31,1:2,32,1:7,33,1:2,34,35,36,37,38,39,40,41,42,43,44,1:4,45,46,47,48,49" +
",50,51,52,53,45,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73" +
",74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98" +
",99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117" +
",118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,13" +
"6,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,1" +
"55,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173," +
"174,24:2")[0];

	private int yy_nxt[][] = unpackFromString(175,70,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,278:2," +
"221,132,191,27,278,222,278,248,271,278,249,264,278,223,250,278,147,224,278," +
"225,278,251,226,28,29,27,28,30,31,278:4,30,278:2,32,27,33,278:2,28,-1:73,34" +
",-1:69,35,-1:78,131,-1:42,36:2,-1:4,36,-1:11,37,-1:10,38,-1:58,39,-1:11,40," +
"-1:57,41,-1:69,42,-1:69,43,-1:14,44,-1:54,45,-1:15,46,-1:53,47,-1:16,48,-1:" +
"52,49,-1:15,50,-1,51,-1:51,52,-1:7,53,-1:10,54,-1:50,55,-1:91,278,276,277:4" +
",278,277:19,-1:4,278:9,-1:2,278:2,277,-1:2,29:53,-1,29:15,-1:12,135,-1:15,1" +
"46,-1:6,58,-1:9,59,-1:9,30:2,136,59,-1:2,30,146,-1:19,135,-1:15,146,-1:6,60" +
",-1:9,61,149,-1:8,133,134,137,61,149,-1,134,146,-1:35,146,-1,63,-1:14,64,-1" +
":9,36:2,-1,64,-1:2,36,146,63,-1:9,65,-1:69,66,-1:67,54:53,-1,54:15,-1:25,27" +
"8,277:5,278,277:3,234,277:15,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278," +
"277:19,-1:4,278:9,-1:2,278:2,277,-1:46,70,-1:69,71,-1:52,153,-1,63,-1:14,64" +
",-1:9,69:2,-1,64,-1:2,69,155,63,-1:34,72:3,-1:2,72,-1,81,-1:2,72,-1:2,72,-1" +
":3,82,-1:9,72:2,139,82,-1,72:4,-1:51,89,-1:78,142,-1:69,143,-1:69,144,-1:69" +
",145,-1:27,62,-1:82,278,277:2,265,277:2,278,277:5,56,277:13,-1:4,278:9,-1:2" +
",278:2,277,-1:13,135,-1:15,146,-1:26,133:2,-1:4,133,146,-1:19,135,-1:15,146" +
",-1:6,60,-1:9,61,-1:9,133,134,137,61,-1:2,134,146,-1:35,146,-1,63,-1:14,64," +
"-1:9,69:2,-1,64,-1:2,69,146,63,-1:64,70,-1:69,71,-1:41,63,-1:14,64,-1:9,138" +
":2,-1,64,-1:2,138,-1,63,-1:64,89,-1:33,107,-1:101,110,-1:36,151,-1:33,148:2" +
",-1:4,148,-1:33,278,277:4,57,278,152,277:18,-1:4,278:9,-1:2,278:2,277,-1:31" +
",63,-1:14,64,-1:9,148:2,-1,64,-1:2,148,-1,63,-1:34,72:3,-1:2,72,-1:4,72,-1:" +
"2,72,-1:13,72:2,-1:3,72:4,-1:31,278,277:5,278,277:7,67,277:11,-1:4,278:9,-1" +
":2,278:2,277,-1:56,148:2,-1:4,148,-1:33,278,277:5,278,277:4,68,277:14,-1:4," +
"278:9,-1:2,278:2,277,-1:22,157,-1:33,138:2,-1:4,138,-1:33,278,277:5,278,277" +
":2,73,277:16,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,74,277:2,278,277:19," +
"-1:4,278:9,-1:2,278:2,277,-1:56,138:2,-1:4,138,-1:33,278,277:5,278,277:5,75" +
",277:13,-1:4,278:9,-1:2,278:2,277,-1,1,105:10,140,105:39,-1,105:2,106,105:1" +
"5,-1:25,278,277:2,76,277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1,1,108:50" +
",141,108:13,109,27,108:3,-1:25,278,277:5,278,277:7,77,277:11,-1:4,278:9,-1:" +
"2,278:2,277,-1,1,111:29,112,111,113,111:3,114,111:2,115,111:11,116,111:2,14" +
"2,111:15,-1:25,278,277:5,278,277:15,78,277:3,-1:4,278:9,-1:2,278:2,277,-1,1" +
",27:50,117,27:2,143,27:11,118,27:3,-1:25,278,277:5,278,277:5,79,277:13,-1:4" +
",278:9,-1:2,278:2,277,-1,1,119:50,120,119:2,144,119:9,121,122,119:4,-1:25,2" +
"78,277:3,80,277,278,277:19,-1:4,278:9,-1:2,278:2,277,-1,1,123:29,124,123,12" +
"5,123:3,126,123:2,127,123:11,128,123:2,145,123:9,129,130,123:4,-1:25,278,27" +
"7:5,278,277:4,83,277:14,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,84,27" +
"7:18,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:8,85,277:10,-1:4,278" +
":9,-1:2,278:2,277,-1:26,278,277:5,278,277:4,86,277:14,-1:4,278:9,-1:2,278:2" +
",277,-1:26,278,277:5,278,277:4,87,277:14,-1:4,278:9,-1:2,278:2,277,-1:26,27" +
"8,277:2,88,277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,9" +
"0,277:18,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,91,277:2,278,277:19,-1:4" +
",278:9,-1:2,278:2,277,-1:26,278,277:5,278,92,277:18,-1:4,278:9,-1:2,278:2,2" +
"77,-1:26,278,277:5,278,277:9,93,277:9,-1:4,278:9,-1:2,278:2,277,-1:26,278,2" +
"77:5,278,277:4,94,277:14,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:3,95,277,2" +
"78,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:4,96,278,277:19,-1:4,278:" +
"9,-1:2,278:2,277,-1:26,278,277:5,278,277:11,97,277:7,-1:4,278:9,-1:2,278:2," +
"277,-1:26,278,277:5,278,277:4,98,277:14,-1:4,278:9,-1:2,278:2,277,-1:26,278" +
",277:4,99,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:3,100,277,278," +
"277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:7,101,277:11,-1:4," +
"278:9,-1:2,278:2,277,-1:26,278,277:2,102,277:2,278,277:19,-1:4,278:9,-1:2,2" +
"78:2,277,-1:26,278,277:2,103,277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:" +
"26,278,277:2,104,277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5" +
",278,277:5,150,277:7,227,277:5,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,27" +
"8,277:3,154,277:15,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:10,156" +
",277:8,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:4,158,277:14,-1:4," +
"278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:10,160,277:8,-1:4,278:9,-1:2,2" +
"78:2,277,-1:26,278,277:5,278,277,162,277:17,-1:4,278:9,-1:2,278:2,277,-1:26" +
",278,277:5,278,164,277:18,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277" +
":4,166,277:14,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:12,168,269," +
"277:5,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277,170,277:17,-1:4,278" +
":9,-1:2,278:2,277,-1:26,278,277:5,278,277:5,171,277:13,-1:4,278:9,-1:2,278:" +
"2,277,-1:26,278,277:5,278,277,172,277:17,-1:4,278:9,-1:2,278:2,277,-1:26,27" +
"8,277:5,278,277:4,261,277:5,173,277:8,-1:4,278:9,-1:2,278:2,277,-1:26,278,2" +
"77:5,278,277:7,174,277:11,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277" +
":13,175,277:5,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:7,176,277:1" +
"1,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:13,177,277:5,-1:4,278:9" +
",-1:2,278:2,277,-1:26,278,277:5,278,277:7,178,277:11,-1:4,278:9,-1:2,278:2," +
"277,-1:26,278,277:5,278,277:12,179,277:6,-1:4,278:9,-1:2,278:2,277,-1:26,27" +
"8,277:5,278,277:9,180,277:9,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,181,2" +
"77:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:5,182,277" +
":13,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:9,183,277:9,-1:4,278:" +
"9,-1:2,278:2,277,-1:26,278,277:5,278,277:13,184,277:5,-1:4,278:9,-1:2,278:2" +
",277,-1:26,278,277:2,185,277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,2" +
"78,277:2,186,277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,187" +
",277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:3,188,2" +
"77:15,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:13,189,277:5,-1:4,2" +
"78:9,-1:2,278:2,277,-1:26,278,277:5,278,277:2,190,277:16,-1:4,278:9,-1:2,27" +
"8:2,277,-1:26,278,277:5,278,192,277:12,193,252,277:4,-1:4,278:9,-1:2,278:2," +
"277,-1:26,278,277:5,278,277:3,194,277:15,-1:4,278:9,-1:2,278:2,277,-1:26,27" +
"8,277:5,278,277,195,277:3,230,277:5,196,277:7,-1:4,278:9,-1:2,278:2,277,-1:" +
"26,278,277:5,278,277:5,197,277:13,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5" +
",278,277:5,198,277:13,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:5,1" +
"99,277:13,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:5,200,277:13,-1" +
":4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:10,267,277,201,277:6,-1:4,2" +
"78:9,-1:2,278:2,277,-1:26,278,277:2,202,277:2,278,277:19,-1:4,278:9,-1:2,27" +
"8:2,277,-1:26,278,277:5,278,203,277:18,-1:4,278:9,-1:2,278:2,277,-1:26,278," +
"277:5,278,277:5,204,277:13,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,27" +
"7:12,205,277:6,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,206,277:2,278,277:" +
"19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:6,207,277:12,-1:4,278:" +
"9,-1:2,278:2,277,-1:26,278,277:5,278,277:3,208,277:15,-1:4,278:9,-1:2,278:2" +
",277,-1:26,278,277:5,278,277:4,209,277:14,-1:4,278:9,-1:2,278:2,277,-1:26,2" +
"78,277:5,278,277:3,210,277:15,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278" +
",211,277:18,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,212,277:2,278,277:19," +
"-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:4,213,277:14,-1:4,278:9,-" +
"1:2,278:2,277,-1:26,278,277:5,278,277:3,214,277:15,-1:4,278:9,-1:2,278:2,27" +
"7,-1:26,278,277:3,215,277,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,27" +
"7:5,278,216,277:18,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:4,217," +
"277:14,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,218,277:18,-1:4,278:9," +
"-1:2,278:2,277,-1:26,278,277:5,278,277:12,219,277:6,-1:4,278:9,-1:2,278:2,2" +
"77,-1:26,278,277:5,278,277,220,277:17,-1:4,278:9,-1:2,278:2,277,-1:26,278,2" +
"77:5,278,228,277:18,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:7,229" +
",277:11,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:4,254,277:6,231,2" +
"55,277:4,256,277,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:11,232,2" +
"77:7,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:4,233,277:14,-1:4,27" +
"8:9,-1:2,278:2,277,-1:26,278,277:5,278,277:4,235,277:10,268,277:3,-1:4,278:" +
"9,-1:2,278:2,277,-1:26,278,277:5,278,277,236,277:5,237,277:11,-1:4,278:9,-1" +
":2,278:2,277,-1:26,278,277:5,278,277:15,238,239,277:2,-1:4,278:9,-1:2,278:2" +
",277,-1:26,278,277:5,278,277:12,240,277:6,-1:4,278:9,-1:2,278:2,277,-1:26,2" +
"78,277:5,278,277,241,277:17,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,242,2" +
"77:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:15,243,27" +
"7:3,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,278,277:10,244,277:8,-1:4,278" +
":9,-1:2,278:2,277,-1:26,278,277:5,278,277:12,245,277:6,-1:4,278:9,-1:2,278:" +
"2,277,-1:26,278,277:5,278,277:4,246,277:14,-1:4,278:9,-1:2,278:2,277,-1:26," +
"278,277:5,278,247,277:18,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,253,277:" +
"2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:4,257,278,277:19,-1:4," +
"278:9,-1:2,278:2,277,-1:26,278,277,258,277:3,278,277:19,-1:4,278:9,-1:2,278" +
":2,277,-1:26,278,277:5,278,277:12,259,277:6,-1:4,278:9,-1:2,278:2,277,-1:26" +
",278,277:5,278,277:12,260,277:6,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,2" +
"78,277,262,277:17,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:5,263,277:19,-1:4" +
",278:9,-1:2,278:2,277,-1:26,278,266,277:4,278,277:19,-1:4,278:9,-1:2,278:2," +
"277,-1:26,278,277:4,270,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:" +
"2,272,277:2,278,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:3,273,277,27" +
"8,277:19,-1:4,278:9,-1:2,278:2,277,-1:26,278,277:2,274,277:2,278,277:19,-1:" +
"4,278:9,-1:2,278:2,277,-1:26,278,277,275,277:3,278,277:19,-1:4,278:9,-1:2,2" +
"78:2,277,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", sym._SYMB_0, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", sym._SYMB_3, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", sym._SYMB_4, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", sym._SYMB_5, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", sym._SYMB_6, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ return cf.newSymbol("", sym._SYMB_7, left_loc(), right_loc()); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", sym._SYMB_8, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ return cf.newSymbol("", sym._SYMB_9, left_loc(), right_loc()); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", sym._SYMB_10, left_loc(), right_loc()); }
					case -13:
						break;
					case 13:
						{ return cf.newSymbol("", sym._SYMB_32, left_loc(), right_loc()); }
					case -14:
						break;
					case 14:
						{ return cf.newSymbol("", sym._SYMB_12, left_loc(), right_loc()); }
					case -15:
						break;
					case 15:
						{ return cf.newSymbol("", sym._SYMB_15, left_loc(), right_loc()); }
					case -16:
						break;
					case 16:
						{ return cf.newSymbol("", sym._SYMB_17, left_loc(), right_loc()); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", sym._SYMB_16, left_loc(), right_loc()); }
					case -18:
						break;
					case 18:
						{ return cf.newSymbol("", sym._SYMB_35, left_loc(), right_loc()); }
					case -19:
						break;
					case 19:
						{ return cf.newSymbol("", sym._SYMB_20, left_loc(), right_loc()); }
					case -20:
						break;
					case 20:
						{ return cf.newSymbol("", sym._SYMB_21, left_loc(), right_loc()); }
					case -21:
						break;
					case 21:
						{ return cf.newSymbol("", sym._SYMB_26, left_loc(), right_loc()); }
					case -22:
						break;
					case 22:
						{ return cf.newSymbol("", sym._SYMB_27, left_loc(), right_loc()); }
					case -23:
						break;
					case 23:
						{ return cf.newSymbol("", sym._SYMB_28, left_loc(), right_loc()); }
					case -24:
						break;
					case 24:
						{ return cf.newSymbol("", sym._SYMB_29, left_loc(), right_loc()); }
					case -25:
						break;
					case 25:
						{ return cf.newSymbol("", sym._SYMB_34, left_loc(), right_loc()); }
					case -26:
						break;
					case 26:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -27:
						break;
					case 27:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -28:
						break;
					case 28:
						{ /* ignore white space. */ }
					case -29:
						break;
					case 29:
						{ /* skip */ }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", sym._INTEGER_, left_loc(), right_loc(), Integer.valueOf(yytext())); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", sym.Octal, left_loc(), right_loc(), yytext().intern()); }
					case -32:
						break;
					case 32:
						{ left = left_loc(); yybegin(STRING); }
					case -33:
						break;
					case 33:
						{ left = left_loc(); yybegin(CHAR); }
					case -34:
						break;
					case 34:
						{ return cf.newSymbol("", sym._SYMB_18, left_loc(), right_loc()); }
					case -35:
						break;
					case 35:
						{ return cf.newSymbol("", sym._SYMB_36, left_loc(), right_loc()); }
					case -36:
						break;
					case 36:
						{ return cf.newSymbol("", sym.CDouble, left_loc(), right_loc(), yytext().intern()); }
					case -37:
						break;
					case 37:
						{ return cf.newSymbol("", sym._SYMB_45, left_loc(), right_loc()); }
					case -38:
						break;
					case 38:
						{ return cf.newSymbol("", sym._SYMB_13, left_loc(), right_loc()); }
					case -39:
						break;
					case 39:
						{ return cf.newSymbol("", sym._SYMB_43, left_loc(), right_loc()); }
					case -40:
						break;
					case 40:
						{ return cf.newSymbol("", sym._SYMB_14, left_loc(), right_loc()); }
					case -41:
						break;
					case 41:
						{ return cf.newSymbol("", sym._SYMB_44, left_loc(), right_loc()); }
					case -42:
						break;
					case 42:
						{ return cf.newSymbol("", sym._SYMB_19, left_loc(), right_loc()); }
					case -43:
						break;
					case 43:
						{ return cf.newSymbol("", sym._SYMB_22, left_loc(), right_loc()); }
					case -44:
						break;
					case 44:
						{ return cf.newSymbol("", sym._SYMB_24, left_loc(), right_loc()); }
					case -45:
						break;
					case 45:
						{ return cf.newSymbol("", sym._SYMB_23, left_loc(), right_loc()); }
					case -46:
						break;
					case 46:
						{ return cf.newSymbol("", sym._SYMB_25, left_loc(), right_loc()); }
					case -47:
						break;
					case 47:
						{ return cf.newSymbol("", sym._SYMB_39, left_loc(), right_loc()); }
					case -48:
						break;
					case 48:
						{ return cf.newSymbol("", sym._SYMB_30, left_loc(), right_loc()); }
					case -49:
						break;
					case 49:
						{ return cf.newSymbol("", sym._SYMB_40, left_loc(), right_loc()); }
					case -50:
						break;
					case 50:
						{ return cf.newSymbol("", sym._SYMB_33, left_loc(), right_loc()); }
					case -51:
						break;
					case 51:
						{ return cf.newSymbol("", sym._SYMB_31, left_loc(), right_loc()); }
					case -52:
						break;
					case 52:
						{ return cf.newSymbol("", sym._SYMB_37, left_loc(), right_loc()); }
					case -53:
						break;
					case 53:
						{ yybegin(COMMENT); }
					case -54:
						break;
					case 54:
						{ /* skip */ }
					case -55:
						break;
					case 55:
						{ return cf.newSymbol("", sym._SYMB_38, left_loc(), right_loc()); }
					case -56:
						break;
					case 56:
						{ return cf.newSymbol("", sym._SYMB_54, left_loc(), right_loc()); }
					case -57:
						break;
					case 57:
						{ return cf.newSymbol("", sym._SYMB_62, left_loc(), right_loc()); }
					case -58:
						break;
					case 58:
						{ return cf.newSymbol("", sym.Unsigned, left_loc(), right_loc(), yytext().intern()); }
					case -59:
						break;
					case 59:
						{ return cf.newSymbol("", sym.Long, left_loc(), right_loc(), yytext().intern()); }
					case -60:
						break;
					case 60:
						{ return cf.newSymbol("", sym.OctalUnsigned, left_loc(), right_loc(), yytext().intern()); }
					case -61:
						break;
					case 61:
						{ return cf.newSymbol("", sym.OctalLong, left_loc(), right_loc(), yytext().intern()); }
					case -62:
						break;
					case 62:
						{ return cf.newSymbol("", sym._SYMB_11, left_loc(), right_loc()); }
					case -63:
						break;
					case 63:
						{ return cf.newSymbol("", sym.CFloat, left_loc(), right_loc(), yytext().intern()); }
					case -64:
						break;
					case 64:
						{ return cf.newSymbol("", sym.CLongDouble, left_loc(), right_loc(), yytext().intern()); }
					case -65:
						break;
					case 65:
						{ return cf.newSymbol("", sym._SYMB_41, left_loc(), right_loc()); }
					case -66:
						break;
					case 66:
						{ return cf.newSymbol("", sym._SYMB_42, left_loc(), right_loc()); }
					case -67:
						break;
					case 67:
						{ return cf.newSymbol("", sym._SYMB_60, left_loc(), right_loc()); }
					case -68:
						break;
					case 68:
						{ return cf.newSymbol("", sym._SYMB_63, left_loc(), right_loc()); }
					case -69:
						break;
					case 69:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), Double.valueOf(yytext())); }
					case -70:
						break;
					case 70:
						{ return cf.newSymbol("", sym.UnsignedLong, left_loc(), right_loc(), yytext().intern()); }
					case -71:
						break;
					case 71:
						{ return cf.newSymbol("", sym.OctalUnsLong, left_loc(), right_loc(), yytext().intern()); }
					case -72:
						break;
					case 72:
						{ return cf.newSymbol("", sym.Hexadecimal, left_loc(), right_loc(), yytext().intern()); }
					case -73:
						break;
					case 73:
						{ return cf.newSymbol("", sym._SYMB_57, left_loc(), right_loc()); }
					case -74:
						break;
					case 74:
						{ return cf.newSymbol("", sym._SYMB_56, left_loc(), right_loc()); }
					case -75:
						break;
					case 75:
						{ return cf.newSymbol("", sym._SYMB_47, left_loc(), right_loc()); }
					case -76:
						break;
					case 76:
						{ return cf.newSymbol("", sym._SYMB_49, left_loc(), right_loc()); }
					case -77:
						break;
					case 77:
						{ return cf.newSymbol("", sym._SYMB_50, left_loc(), right_loc()); }
					case -78:
						break;
					case 78:
						{ return cf.newSymbol("", sym._SYMB_64, left_loc(), right_loc()); }
					case -79:
						break;
					case 79:
						{ return cf.newSymbol("", sym._SYMB_61, left_loc(), right_loc()); }
					case -80:
						break;
					case 80:
						{ return cf.newSymbol("", sym._SYMB_76, left_loc(), right_loc()); }
					case -81:
						break;
					case 81:
						{ return cf.newSymbol("", sym.HexUnsigned, left_loc(), right_loc(), yytext().intern()); }
					case -82:
						break;
					case 82:
						{ return cf.newSymbol("", sym.HexLong, left_loc(), right_loc(), yytext().intern()); }
					case -83:
						break;
					case 83:
						{ return cf.newSymbol("", sym._SYMB_59, left_loc(), right_loc()); }
					case -84:
						break;
					case 84:
						{ return cf.newSymbol("", sym._SYMB_74, left_loc(), right_loc()); }
					case -85:
						break;
					case 85:
						{ return cf.newSymbol("", sym._SYMB_48, left_loc(), right_loc()); }
					case -86:
						break;
					case 86:
						{ return cf.newSymbol("", sym._SYMB_51, left_loc(), right_loc()); }
					case -87:
						break;
					case 87:
						{ return cf.newSymbol("", sym._SYMB_67, left_loc(), right_loc()); }
					case -88:
						break;
					case 88:
						{ return cf.newSymbol("", sym._SYMB_78, left_loc(), right_loc()); }
					case -89:
						break;
					case 89:
						{ return cf.newSymbol("", sym.HexUnsLong, left_loc(), right_loc(), yytext().intern()); }
					case -90:
						break;
					case 90:
						{ return cf.newSymbol("", sym._SYMB_58, left_loc(), right_loc()); }
					case -91:
						break;
					case 91:
						{ return cf.newSymbol("", sym._SYMB_55, left_loc(), right_loc()); }
					case -92:
						break;
					case 92:
						{ return cf.newSymbol("", sym._SYMB_66, left_loc(), right_loc()); }
					case -93:
						break;
					case 93:
						{ return cf.newSymbol("", sym._SYMB_70, left_loc(), right_loc()); }
					case -94:
						break;
					case 94:
						{ return cf.newSymbol("", sym._SYMB_71, left_loc(), right_loc()); }
					case -95:
						break;
					case 95:
						{ return cf.newSymbol("", sym._SYMB_68, left_loc(), right_loc()); }
					case -96:
						break;
					case 96:
						{ return cf.newSymbol("", sym._SYMB_69, left_loc(), right_loc()); }
					case -97:
						break;
					case 97:
						{ return cf.newSymbol("", sym._SYMB_72, left_loc(), right_loc()); }
					case -98:
						break;
					case 98:
						{ return cf.newSymbol("", sym._SYMB_53, left_loc(), right_loc()); }
					case -99:
						break;
					case 99:
						{ return cf.newSymbol("", sym._SYMB_73, left_loc(), right_loc()); }
					case -100:
						break;
					case 100:
						{ return cf.newSymbol("", sym._SYMB_75, left_loc(), right_loc()); }
					case -101:
						break;
					case 101:
						{ return cf.newSymbol("", sym._SYMB_65, left_loc(), right_loc()); }
					case -102:
						break;
					case 102:
						{ return cf.newSymbol("", sym._SYMB_52, left_loc(), right_loc()); }
					case -103:
						break;
					case 103:
						{ return cf.newSymbol("", sym._SYMB_77, left_loc(), right_loc()); }
					case -104:
						break;
					case 104:
						{ return cf.newSymbol("", sym._SYMB_46, left_loc(), right_loc()); }
					case -105:
						break;
					case 105:
						{ /* skip */ }
					case -106:
						break;
					case 106:
						{ /* skip */ }
					case -107:
						break;
					case 107:
						{ yybegin(YYINITIAL); }
					case -108:
						break;
					case 108:
						{ yybegin(CHAREND); return cf.newSymbol("", sym._CHAR_, left, right_loc(), Character.valueOf(yytext().charAt(0))); }
					case -109:
						break;
					case 109:
						{ yybegin(CHARESC); }
					case -110:
						break;
					case 110:
						{ throw new Error("Unterminated character literal on line " + left.getLine() ); }
					case -111:
						break;
					case 111:
						{ yybegin(CHAREND); return cf.newSymbol("", sym._CHAR_, left, right_loc(), Character.valueOf(yytext().charAt(0))); }
					case -112:
						break;
					case 112:
						{ yybegin(CHAREND); return cf.newSymbol("", sym._CHAR_, left, right_loc(), Character.valueOf('\f')); }
					case -113:
						break;
					case 113:
						{ yybegin(CHAREND); return cf.newSymbol("", sym._CHAR_, left, right_loc(), Character.valueOf('\n')); }
					case -114:
						break;
					case 114:
						{ yybegin(CHAREND); return cf.newSymbol("", sym._CHAR_, left, right_loc(), Character.valueOf('\t')); }
					case -115:
						break;
					case 115:
						{ yybegin(CHAREND); return cf.newSymbol("", sym._CHAR_, left, right_loc(), Character.valueOf('\r')); }
					case -116:
						break;
					case 116:
						{ throw new Error("Unterminated character literal on line " + left.getLine() ); }
					case -117:
						break;
					case 117:
						{ throw new Error("Unterminated character literal on line " + left.getLine() ); }
					case -118:
						break;
					case 118:
						{yybegin(YYINITIAL);}
					case -119:
						break;
					case 119:
						{ pstring += yytext(); }
					case -120:
						break;
					case 120:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -121:
						break;
					case 121:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return cf.newSymbol("", sym._STRING_, left, right_loc(), foo.intern()); }
					case -122:
						break;
					case 122:
						{ yybegin(ESCAPED); }
					case -123:
						break;
					case 123:
						{ pstring += yytext(); yybegin(STRING); }
					case -124:
						break;
					case 124:
						{ pstring += "\f"; yybegin(STRING); }
					case -125:
						break;
					case 125:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -126:
						break;
					case 126:
						{ pstring += "\t"; yybegin(STRING); }
					case -127:
						break;
					case 127:
						{ pstring += "\r"; yybegin(STRING); }
					case -128:
						break;
					case 128:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -129:
						break;
					case 129:
						{ pstring += "\""; yybegin(STRING); }
					case -130:
						break;
					case 130:
						{ pstring += "\\"; yybegin(STRING); }
					case -131:
						break;
					case 132:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -132:
						break;
					case 133:
						{ return cf.newSymbol("", sym._INTEGER_, left_loc(), right_loc(), Integer.valueOf(yytext())); }
					case -133:
						break;
					case 134:
						{ return cf.newSymbol("", sym.Octal, left_loc(), right_loc(), yytext().intern()); }
					case -134:
						break;
					case 135:
						{ return cf.newSymbol("", sym.CDouble, left_loc(), right_loc(), yytext().intern()); }
					case -135:
						break;
					case 136:
						{ return cf.newSymbol("", sym.Unsigned, left_loc(), right_loc(), yytext().intern()); }
					case -136:
						break;
					case 137:
						{ return cf.newSymbol("", sym.OctalUnsigned, left_loc(), right_loc(), yytext().intern()); }
					case -137:
						break;
					case 138:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), Double.valueOf(yytext())); }
					case -138:
						break;
					case 139:
						{ return cf.newSymbol("", sym.HexUnsigned, left_loc(), right_loc(), yytext().intern()); }
					case -139:
						break;
					case 140:
						{ /* skip */ }
					case -140:
						break;
					case 141:
						{ yybegin(CHAREND); return cf.newSymbol("", sym._CHAR_, left, right_loc(), Character.valueOf(yytext().charAt(0))); }
					case -141:
						break;
					case 142:
						{ throw new Error("Unterminated character literal on line " + left.getLine() ); }
					case -142:
						break;
					case 143:
						{ throw new Error("Unterminated character literal on line " + left.getLine() ); }
					case -143:
						break;
					case 144:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -144:
						break;
					case 145:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -145:
						break;
					case 147:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -146:
						break;
					case 148:
						{ return cf.newSymbol("", sym.CDouble, left_loc(), right_loc(), yytext().intern()); }
					case -147:
						break;
					case 150:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -148:
						break;
					case 152:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -149:
						break;
					case 154:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -150:
						break;
					case 156:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -151:
						break;
					case 158:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -152:
						break;
					case 160:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -153:
						break;
					case 162:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -154:
						break;
					case 164:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -155:
						break;
					case 166:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -156:
						break;
					case 168:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -157:
						break;
					case 170:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -158:
						break;
					case 171:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -159:
						break;
					case 172:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -160:
						break;
					case 173:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -161:
						break;
					case 174:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -162:
						break;
					case 175:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -163:
						break;
					case 176:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -164:
						break;
					case 177:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -165:
						break;
					case 178:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -166:
						break;
					case 179:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -167:
						break;
					case 180:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -168:
						break;
					case 181:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -169:
						break;
					case 182:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -170:
						break;
					case 183:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -171:
						break;
					case 184:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -172:
						break;
					case 185:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -173:
						break;
					case 186:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -174:
						break;
					case 187:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -175:
						break;
					case 188:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -176:
						break;
					case 189:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -177:
						break;
					case 190:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -178:
						break;
					case 191:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -179:
						break;
					case 192:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -180:
						break;
					case 193:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -181:
						break;
					case 194:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -182:
						break;
					case 195:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -183:
						break;
					case 196:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -184:
						break;
					case 197:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -185:
						break;
					case 198:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -186:
						break;
					case 199:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -187:
						break;
					case 200:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -188:
						break;
					case 201:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -189:
						break;
					case 202:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -190:
						break;
					case 203:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -191:
						break;
					case 204:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -192:
						break;
					case 205:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -193:
						break;
					case 206:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -194:
						break;
					case 207:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -195:
						break;
					case 208:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -196:
						break;
					case 209:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -197:
						break;
					case 210:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -198:
						break;
					case 211:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -199:
						break;
					case 212:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -200:
						break;
					case 213:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -201:
						break;
					case 214:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -202:
						break;
					case 215:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -203:
						break;
					case 216:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -204:
						break;
					case 217:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -205:
						break;
					case 218:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -206:
						break;
					case 219:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -207:
						break;
					case 220:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -208:
						break;
					case 221:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -209:
						break;
					case 222:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -210:
						break;
					case 223:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -211:
						break;
					case 224:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -212:
						break;
					case 225:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -213:
						break;
					case 226:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -214:
						break;
					case 227:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -215:
						break;
					case 228:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -216:
						break;
					case 229:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -217:
						break;
					case 230:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -218:
						break;
					case 231:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -219:
						break;
					case 232:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -220:
						break;
					case 233:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -221:
						break;
					case 234:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -222:
						break;
					case 235:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -223:
						break;
					case 236:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -224:
						break;
					case 237:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -225:
						break;
					case 238:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -226:
						break;
					case 239:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -227:
						break;
					case 240:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -228:
						break;
					case 241:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -229:
						break;
					case 242:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -230:
						break;
					case 243:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -231:
						break;
					case 244:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -232:
						break;
					case 245:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -233:
						break;
					case 246:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -234:
						break;
					case 247:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -235:
						break;
					case 248:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -236:
						break;
					case 249:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -237:
						break;
					case 250:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -238:
						break;
					case 251:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -239:
						break;
					case 252:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -240:
						break;
					case 253:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -241:
						break;
					case 254:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -242:
						break;
					case 255:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -243:
						break;
					case 256:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -244:
						break;
					case 257:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -245:
						break;
					case 258:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -246:
						break;
					case 259:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -247:
						break;
					case 260:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -248:
						break;
					case 261:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -249:
						break;
					case 262:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -250:
						break;
					case 263:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -251:
						break;
					case 264:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -252:
						break;
					case 265:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -253:
						break;
					case 266:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -254:
						break;
					case 267:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -255:
						break;
					case 268:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -256:
						break;
					case 269:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -257:
						break;
					case 270:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -258:
						break;
					case 271:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -259:
						break;
					case 272:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -260:
						break;
					case 273:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -261:
						break;
					case 274:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -262:
						break;
					case 275:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -263:
						break;
					case 276:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -264:
						break;
					case 277:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -265:
						break;
					case 278:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -266:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
