// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Abstract  extends Parameter_declaration {
  public final ListDeclaration_specifier listdeclaration_specifier_;
  public final Abstract_declarator abstract_declarator_;
  public Abstract(ListDeclaration_specifier p1, Abstract_declarator p2) { listdeclaration_specifier_ = p1; abstract_declarator_ = p2; }

  public <R,A> R accept(c.Absyn.Parameter_declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Abstract) {
      c.Absyn.Abstract x = (c.Absyn.Abstract)o;
      return this.listdeclaration_specifier_.equals(x.listdeclaration_specifier_) && this.abstract_declarator_.equals(x.abstract_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listdeclaration_specifier_.hashCode())+this.abstract_declarator_.hashCode();
  }


}
