// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class AssignRight  extends Assignment_op {
  public AssignRight() { }

  public <R,A> R accept(c.Absyn.Assignment_op.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.AssignRight) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
