// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class BeginPointer  extends Declarator {
  public final Pointer pointer_;
  public final Direct_declarator direct_declarator_;
  public BeginPointer(Pointer p1, Direct_declarator p2) { pointer_ = p1; direct_declarator_ = p2; }

  public <R,A> R accept(c.Absyn.Declarator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.BeginPointer) {
      c.Absyn.BeginPointer x = (c.Absyn.BeginPointer)o;
      return this.pointer_.equals(x.pointer_) && this.direct_declarator_.equals(x.direct_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pointer_.hashCode())+this.direct_declarator_.hashCode();
  }


}
