// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class CompS  extends Stm {
  public final Compound_stm compound_stm_;
  public CompS(Compound_stm p1) { compound_stm_ = p1; }

  public <R,A> R accept(c.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.CompS) {
      c.Absyn.CompS x = (c.Absyn.CompS)o;
      return this.compound_stm_.equals(x.compound_stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.compound_stm_.hashCode();
  }


}
