// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Complement  extends Unary_operator {
  public Complement() { }

  public <R,A> R accept(c.Absyn.Unary_operator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Complement) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
