// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Const  extends Type_qualifier {
  public Const() { }

  public <R,A> R accept(c.Absyn.Type_qualifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Const) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
