// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Dec implements java.io.Serializable {
  public abstract <R,A> R accept(Dec.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.NoDeclarator p, A arg);
    public R visit(c.Absyn.Declarators p, A arg);

  }

}
