// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Declaration_specifier implements java.io.Serializable {
  public abstract <R,A> R accept(Declaration_specifier.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Type p, A arg);
    public R visit(c.Absyn.Storage p, A arg);
    public R visit(c.Absyn.SpecProp p, A arg);

  }

}
