// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Dir_abs_dec implements java.io.Serializable {
  public abstract <R,A> R accept(Dir_abs_dec.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.WithinParentes p, A arg);
    public R visit(c.Absyn.Array p, A arg);
    public R visit(c.Absyn.InitiatedArray p, A arg);
    public R visit(c.Absyn.UnInitiated p, A arg);
    public R visit(c.Absyn.Initiated p, A arg);
    public R visit(c.Absyn.OldFunction p, A arg);
    public R visit(c.Absyn.NewFunction p, A arg);
    public R visit(c.Absyn.OldFuncExpr p, A arg);
    public R visit(c.Absyn.NewFuncExpr p, A arg);

  }

}
