// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Direct_declarator implements java.io.Serializable {
  public abstract <R,A> R accept(Direct_declarator.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Name p, A arg);
    public R visit(c.Absyn.ParenDecl p, A arg);
    public R visit(c.Absyn.InnitArray p, A arg);
    public R visit(c.Absyn.Incomplete p, A arg);
    public R visit(c.Absyn.NewFuncDec p, A arg);
    public R visit(c.Absyn.OldFuncDef p, A arg);
    public R visit(c.Absyn.OldFuncDec p, A arg);

  }

}
