// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Ebytestype  extends Exp {
  public final Type_name type_name_;
  public Ebytestype(Type_name p1) { type_name_ = p1; }

  public <R,A> R accept(c.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Ebytestype) {
      c.Absyn.Ebytestype x = (c.Absyn.Ebytestype)o;
      return this.type_name_.equals(x.type_name_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_name_.hashCode();
  }


}
