// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Eclongdouble  extends Constant {
  public final String clongdouble_;
  public Eclongdouble(String p1) { clongdouble_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Eclongdouble) {
      c.Absyn.Eclongdouble x = (c.Absyn.Eclongdouble)o;
      return this.clongdouble_.equals(x.clongdouble_);
    }
    return false;
  }

  public int hashCode() {
    return this.clongdouble_.hashCode();
  }


}
