// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Econst  extends Exp {
  public final Constant constant_;
  public Econst(Constant p1) { constant_ = p1; }

  public <R,A> R accept(c.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Econst) {
      c.Absyn.Econst x = (c.Absyn.Econst)o;
      return this.constant_.equals(x.constant_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_.hashCode();
  }


}
