// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Ehexadec  extends Constant {
  public final String hexadecimal_;
  public Ehexadec(String p1) { hexadecimal_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Ehexadec) {
      c.Absyn.Ehexadec x = (c.Absyn.Ehexadec)o;
      return this.hexadecimal_.equals(x.hexadecimal_);
    }
    return false;
  }

  public int hashCode() {
    return this.hexadecimal_.hashCode();
  }


}
