// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Eint  extends Constant {
  public final Integer integer_;
  public Eint(Integer p1) { integer_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Eint) {
      c.Absyn.Eint x = (c.Absyn.Eint)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
