// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Eoctalunsign  extends Constant {
  public final String octalunsigned_;
  public Eoctalunsign(String p1) { octalunsigned_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Eoctalunsign) {
      c.Absyn.Eoctalunsign x = (c.Absyn.Eoctalunsign)o;
      return this.octalunsigned_.equals(x.octalunsigned_);
    }
    return false;
  }

  public int hashCode() {
    return this.octalunsigned_.hashCode();
  }


}
