// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Eoctal  extends Constant {
  public final String octal_;
  public Eoctal(String p1) { octal_ = p1; }

  public <R,A> R accept(c.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Eoctal) {
      c.Absyn.Eoctal x = (c.Absyn.Eoctal)o;
      return this.octal_.equals(x.octal_);
    }
    return false;
  }

  public int hashCode() {
    return this.octal_.hashCode();
  }


}
