// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Epostinc  extends Exp {
  public final Exp exp_;
  public Epostinc(Exp p1) { exp_ = p1; }

  public <R,A> R accept(c.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Epostinc) {
      c.Absyn.Epostinc x = (c.Absyn.Epostinc)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
