// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class ExprS  extends Stm {
  public final Expression_stm expression_stm_;
  public ExprS(Expression_stm p1) { expression_stm_ = p1; }

  public <R,A> R accept(c.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.ExprS) {
      c.Absyn.ExprS x = (c.Absyn.ExprS)o;
      return this.expression_stm_.equals(x.expression_stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.expression_stm_.hashCode();
  }


}
