// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class ExtendedType  extends Type_name {
  public final ListSpec_qual listspec_qual_;
  public final Abstract_declarator abstract_declarator_;
  public ExtendedType(ListSpec_qual p1, Abstract_declarator p2) { listspec_qual_ = p1; abstract_declarator_ = p2; }

  public <R,A> R accept(c.Absyn.Type_name.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.ExtendedType) {
      c.Absyn.ExtendedType x = (c.Absyn.ExtendedType)o;
      return this.listspec_qual_.equals(x.listspec_qual_) && this.abstract_declarator_.equals(x.abstract_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listspec_qual_.hashCode())+this.abstract_declarator_.hashCode();
  }


}
