// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class External_declaration implements java.io.Serializable {
  public abstract <R,A> R accept(External_declaration.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Afunc p, A arg);
    public R visit(c.Absyn.Global p, A arg);

  }

}
