// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Global  extends External_declaration {
  public final Dec dec_;
  public Global(Dec p1) { dec_ = p1; }

  public <R,A> R accept(c.Absyn.External_declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Global) {
      c.Absyn.Global x = (c.Absyn.Global)o;
      return this.dec_.equals(x.dec_);
    }
    return false;
  }

  public int hashCode() {
    return this.dec_.hashCode();
  }


}
