// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Initiated  extends Dir_abs_dec {
  public final Dir_abs_dec dir_abs_dec_;
  public final Constant_expression constant_expression_;
  public Initiated(Dir_abs_dec p1, Constant_expression p2) { dir_abs_dec_ = p1; constant_expression_ = p2; }

  public <R,A> R accept(c.Absyn.Dir_abs_dec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Initiated) {
      c.Absyn.Initiated x = (c.Absyn.Initiated)o;
      return this.dir_abs_dec_.equals(x.dir_abs_dec_) && this.constant_expression_.equals(x.constant_expression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.dir_abs_dec_.hashCode())+this.constant_expression_.hashCode();
  }


}
