// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class InitiatedArray  extends Dir_abs_dec {
  public final Constant_expression constant_expression_;
  public InitiatedArray(Constant_expression p1) { constant_expression_ = p1; }

  public <R,A> R accept(c.Absyn.Dir_abs_dec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.InitiatedArray) {
      c.Absyn.InitiatedArray x = (c.Absyn.InitiatedArray)o;
      return this.constant_expression_.equals(x.constant_expression_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_expression_.hashCode();
  }


}
