// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Iter_stm implements java.io.Serializable {
  public abstract <R,A> R accept(Iter_stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.SiterOne p, A arg);
    public R visit(c.Absyn.SiterTwo p, A arg);
    public R visit(c.Absyn.SiterThree p, A arg);
    public R visit(c.Absyn.SiterFour p, A arg);

  }

}
