// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Labeled_stm implements java.io.Serializable {
  public abstract <R,A> R accept(Labeled_stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.SlabelOne p, A arg);
    public R visit(c.Absyn.SlabelTwo p, A arg);
    public R visit(c.Absyn.SlabelThree p, A arg);

  }

}
