// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class LabelS  extends Stm {
  public final Labeled_stm labeled_stm_;
  public LabelS(Labeled_stm p1) { labeled_stm_ = p1; }

  public <R,A> R accept(c.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.LabelS) {
      c.Absyn.LabelS x = (c.Absyn.LabelS)o;
      return this.labeled_stm_.equals(x.labeled_stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.labeled_stm_.hashCode();
  }


}
