// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class NewFuncInt  extends Function_def {
  public final Declarator declarator_;
  public final Compound_stm compound_stm_;
  public NewFuncInt(Declarator p1, Compound_stm p2) { declarator_ = p1; compound_stm_ = p2; }

  public <R,A> R accept(c.Absyn.Function_def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.NewFuncInt) {
      c.Absyn.NewFuncInt x = (c.Absyn.NewFuncInt)o;
      return this.declarator_.equals(x.declarator_) && this.compound_stm_.equals(x.compound_stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.declarator_.hashCode())+this.compound_stm_.hashCode();
  }


}
