// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class OldFuncDec  extends Direct_declarator {
  public final Direct_declarator direct_declarator_;
  public OldFuncDec(Direct_declarator p1) { direct_declarator_ = p1; }

  public <R,A> R accept(c.Absyn.Direct_declarator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.OldFuncDec) {
      c.Absyn.OldFuncDec x = (c.Absyn.OldFuncDec)o;
      return this.direct_declarator_.equals(x.direct_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return this.direct_declarator_.hashCode();
  }


}
