// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Parameter_declarations implements java.io.Serializable {
  public abstract <R,A> R accept(Parameter_declarations.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.ParamDec p, A arg);
    public R visit(c.Absyn.MoreParamDec p, A arg);

  }

}
