// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class ParenDecl  extends Direct_declarator {
  public final Declarator declarator_;
  public ParenDecl(Declarator p1) { declarator_ = p1; }

  public <R,A> R accept(c.Absyn.Direct_declarator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.ParenDecl) {
      c.Absyn.ParenDecl x = (c.Absyn.ParenDecl)o;
      return this.declarator_.equals(x.declarator_);
    }
    return false;
  }

  public int hashCode() {
    return this.declarator_.hashCode();
  }


}
