// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class QualSpec  extends Spec_qual {
  public final Type_qualifier type_qualifier_;
  public QualSpec(Type_qualifier p1) { type_qualifier_ = p1; }

  public <R,A> R accept(c.Absyn.Spec_qual.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.QualSpec) {
      c.Absyn.QualSpec x = (c.Absyn.QualSpec)o;
      return this.type_qualifier_.equals(x.type_qualifier_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_qualifier_.hashCode();
  }


}
