// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Selection_stm implements java.io.Serializable {
  public abstract <R,A> R accept(Selection_stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.SselOne p, A arg);
    public R visit(c.Absyn.SselTwo p, A arg);
    public R visit(c.Absyn.SselThree p, A arg);

  }

}
