// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class SiterFour  extends Iter_stm {
  public final Expression_stm expression_stm_1, expression_stm_2;
  public final Exp exp_;
  public final Stm stm_;
  public SiterFour(Expression_stm p1, Expression_stm p2, Exp p3, Stm p4) { expression_stm_1 = p1; expression_stm_2 = p2; exp_ = p3; stm_ = p4; }

  public <R,A> R accept(c.Absyn.Iter_stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.SiterFour) {
      c.Absyn.SiterFour x = (c.Absyn.SiterFour)o;
      return this.expression_stm_1.equals(x.expression_stm_1) && this.expression_stm_2.equals(x.expression_stm_2) && this.exp_.equals(x.exp_) && this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.expression_stm_1.hashCode())+this.expression_stm_2.hashCode())+this.exp_.hashCode())+this.stm_.hashCode();
  }


}
