// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class SiterThree  extends Iter_stm {
  public final Expression_stm expression_stm_1, expression_stm_2;
  public final Stm stm_;
  public SiterThree(Expression_stm p1, Expression_stm p2, Stm p3) { expression_stm_1 = p1; expression_stm_2 = p2; stm_ = p3; }

  public <R,A> R accept(c.Absyn.Iter_stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.SiterThree) {
      c.Absyn.SiterThree x = (c.Absyn.SiterThree)o;
      return this.expression_stm_1.equals(x.expression_stm_1) && this.expression_stm_2.equals(x.expression_stm_2) && this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expression_stm_1.hashCode())+this.expression_stm_2.hashCode())+this.stm_.hashCode();
  }


}
