// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class SjumpFive  extends Jump_stm {
  public final Exp exp_;
  public SjumpFive(Exp p1) { exp_ = p1; }

  public <R,A> R accept(c.Absyn.Jump_stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.SjumpFive) {
      c.Absyn.SjumpFive x = (c.Absyn.SjumpFive)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
