// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Storage_class_specifier implements java.io.Serializable {
  public abstract <R,A> R accept(Storage_class_specifier.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.MyType p, A arg);
    public R visit(c.Absyn.GlobalPrograms p, A arg);
    public R visit(c.Absyn.LocalProgram p, A arg);
    public R visit(c.Absyn.LocalBlock p, A arg);
    public R visit(c.Absyn.LocalReg p, A arg);

  }

}
