// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Struct_declarator implements java.io.Serializable {
  public abstract <R,A> R accept(Struct_declarator.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Decl p, A arg);
    public R visit(c.Absyn.Field p, A arg);
    public R visit(c.Absyn.DecField p, A arg);

  }

}
