// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Structen  extends Struct_dec {
  public final ListSpec_qual listspec_qual_;
  public final ListStruct_declarator liststruct_declarator_;
  public Structen(ListSpec_qual p1, ListStruct_declarator p2) { listspec_qual_ = p1; liststruct_declarator_ = p2; }

  public <R,A> R accept(c.Absyn.Struct_dec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Structen) {
      c.Absyn.Structen x = (c.Absyn.Structen)o;
      return this.listspec_qual_.equals(x.listspec_qual_) && this.liststruct_declarator_.equals(x.liststruct_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listspec_qual_.hashCode())+this.liststruct_declarator_.hashCode();
  }


}
