// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Tstruct  extends Type_specifier {
  public final Struct_or_union_spec struct_or_union_spec_;
  public Tstruct(Struct_or_union_spec p1) { struct_or_union_spec_ = p1; }

  public <R,A> R accept(c.Absyn.Type_specifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Tstruct) {
      c.Absyn.Tstruct x = (c.Absyn.Tstruct)o;
      return this.struct_or_union_spec_.equals(x.struct_or_union_spec_);
    }
    return false;
  }

  public int hashCode() {
    return this.struct_or_union_spec_.hashCode();
  }


}
