// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Type_name implements java.io.Serializable {
  public abstract <R,A> R accept(Type_name.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.PlainType p, A arg);
    public R visit(c.Absyn.ExtendedType p, A arg);

  }

}
