// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public abstract class Unary_operator implements java.io.Serializable {
  public abstract <R,A> R accept(Unary_operator.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(c.Absyn.Address p, A arg);
    public R visit(c.Absyn.Indirection p, A arg);
    public R visit(c.Absyn.Plus p, A arg);
    public R visit(c.Absyn.Negative p, A arg);
    public R visit(c.Absyn.Complement p, A arg);
    public R visit(c.Absyn.Logicalneg p, A arg);

  }

}
