// File generated by the BNF Converter (bnfc 2.9.5).

package c.Absyn;

public class Unique  extends Struct_or_union_spec {
  public final Struct_or_union struct_or_union_;
  public final ListStruct_dec liststruct_dec_;
  public Unique(Struct_or_union p1, ListStruct_dec p2) { struct_or_union_ = p1; liststruct_dec_ = p2; }

  public <R,A> R accept(c.Absyn.Struct_or_union_spec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof c.Absyn.Unique) {
      c.Absyn.Unique x = (c.Absyn.Unique)o;
      return this.struct_or_union_.equals(x.struct_or_union_) && this.liststruct_dec_.equals(x.liststruct_dec_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.struct_or_union_.hashCode())+this.liststruct_dec_.hashCode();
  }


}
