// File generated by the BNF Converter (bnfc 2.9.5).

package c;

/** All Visitor */

public interface AllVisitor<R,A> extends
  c.Absyn.Program.Visitor<R,A>,
  c.Absyn.External_declaration.Visitor<R,A>,
  c.Absyn.Function_def.Visitor<R,A>,
  c.Absyn.Dec.Visitor<R,A>,
  c.Absyn.Declaration_specifier.Visitor<R,A>,
  c.Absyn.Init_declarator.Visitor<R,A>,
  c.Absyn.Type_specifier.Visitor<R,A>,
  c.Absyn.Storage_class_specifier.Visitor<R,A>,
  c.Absyn.Type_qualifier.Visitor<R,A>,
  c.Absyn.Struct_or_union_spec.Visitor<R,A>,
  c.Absyn.Struct_or_union.Visitor<R,A>,
  c.Absyn.Struct_dec.Visitor<R,A>,
  c.Absyn.Spec_qual.Visitor<R,A>,
  c.Absyn.Struct_declarator.Visitor<R,A>,
  c.Absyn.Enum_specifier.Visitor<R,A>,
  c.Absyn.Enumerator.Visitor<R,A>,
  c.Absyn.Declarator.Visitor<R,A>,
  c.Absyn.Direct_declarator.Visitor<R,A>,
  c.Absyn.Pointer.Visitor<R,A>,
  c.Absyn.Parameter_type.Visitor<R,A>,
  c.Absyn.Parameter_declarations.Visitor<R,A>,
  c.Absyn.Parameter_declaration.Visitor<R,A>,
  c.Absyn.Initializer.Visitor<R,A>,
  c.Absyn.Initializers.Visitor<R,A>,
  c.Absyn.Type_name.Visitor<R,A>,
  c.Absyn.Abstract_declarator.Visitor<R,A>,
  c.Absyn.Dir_abs_dec.Visitor<R,A>,
  c.Absyn.Stm.Visitor<R,A>,
  c.Absyn.Labeled_stm.Visitor<R,A>,
  c.Absyn.Compound_stm.Visitor<R,A>,
  c.Absyn.Expression_stm.Visitor<R,A>,
  c.Absyn.Selection_stm.Visitor<R,A>,
  c.Absyn.Iter_stm.Visitor<R,A>,
  c.Absyn.Jump_stm.Visitor<R,A>,
  c.Absyn.Exp.Visitor<R,A>,
  c.Absyn.Constant.Visitor<R,A>,
  c.Absyn.Constant_expression.Visitor<R,A>,
  c.Absyn.Unary_operator.Visitor<R,A>,
  c.Absyn.Assignment_op.Visitor<R,A>
{}
