// File generated by the BNF Converter (bnfc 2.9.5).

package c;

/** Fold Visitor */
public abstract class FoldVisitor<R,A> implements AllVisitor<R,A> {
    public abstract R leaf(A arg);
    public abstract R combine(R x, R y, A arg);

/* Program */
    public R visit(c.Absyn.Progr p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.External_declaration x : p.listexternal_declaration_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* External_declaration */
    public R visit(c.Absyn.Afunc p, A arg) {
      R r = leaf(arg);
      r = combine(p.function_def_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Global p, A arg) {
      R r = leaf(arg);
      r = combine(p.dec_.accept(this, arg), r, arg);
      return r;
    }

/* Function_def */
    public R visit(c.Absyn.OldFunc p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Declaration_specifier x : p.listdeclaration_specifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.declarator_.accept(this, arg), r, arg);
      for (c.Absyn.Dec x : p.listdec_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.compound_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.NewFunc p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Declaration_specifier x : p.listdeclaration_specifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.declarator_.accept(this, arg), r, arg);
      r = combine(p.compound_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.OldFuncInt p, A arg) {
      R r = leaf(arg);
      r = combine(p.declarator_.accept(this, arg), r, arg);
      for (c.Absyn.Dec x : p.listdec_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.compound_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.NewFuncInt p, A arg) {
      R r = leaf(arg);
      r = combine(p.declarator_.accept(this, arg), r, arg);
      r = combine(p.compound_stm_.accept(this, arg), r, arg);
      return r;
    }

/* Dec */
    public R visit(c.Absyn.NoDeclarator p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Declaration_specifier x : p.listdeclaration_specifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.Declarators p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Declaration_specifier x : p.listdeclaration_specifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (c.Absyn.Init_declarator x : p.listinit_declarator_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Declaration_specifier */
    public R visit(c.Absyn.Type p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_specifier_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Storage p, A arg) {
      R r = leaf(arg);
      r = combine(p.storage_class_specifier_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SpecProp p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_qualifier_.accept(this, arg), r, arg);
      return r;
    }

/* Init_declarator */
    public R visit(c.Absyn.OnlyDecl p, A arg) {
      R r = leaf(arg);
      r = combine(p.declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.InitDecl p, A arg) {
      R r = leaf(arg);
      r = combine(p.declarator_.accept(this, arg), r, arg);
      r = combine(p.initializer_.accept(this, arg), r, arg);
      return r;
    }

/* Type_specifier */
    public R visit(c.Absyn.Tvoid p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tchar p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tshort p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tint p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tlong p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tfloat p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tdouble p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tsigned p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tunsigned p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Tstruct p, A arg) {
      R r = leaf(arg);
      r = combine(p.struct_or_union_spec_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Tenum p, A arg) {
      R r = leaf(arg);
      r = combine(p.enum_specifier_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Tname p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Storage_class_specifier */
    public R visit(c.Absyn.MyType p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.GlobalPrograms p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.LocalProgram p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.LocalBlock p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.LocalReg p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Type_qualifier */
    public R visit(c.Absyn.Const p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.NoOptim p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Struct_or_union_spec */
    public R visit(c.Absyn.Tag p, A arg) {
      R r = leaf(arg);
      r = combine(p.struct_or_union_.accept(this, arg), r, arg);
      for (c.Absyn.Struct_dec x : p.liststruct_dec_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.Unique p, A arg) {
      R r = leaf(arg);
      r = combine(p.struct_or_union_.accept(this, arg), r, arg);
      for (c.Absyn.Struct_dec x : p.liststruct_dec_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.TagType p, A arg) {
      R r = leaf(arg);
      r = combine(p.struct_or_union_.accept(this, arg), r, arg);
      return r;
    }

/* Struct_or_union */
    public R visit(c.Absyn.Struct p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Union p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Struct_dec */
    public R visit(c.Absyn.Structen p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Spec_qual x : p.listspec_qual_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (c.Absyn.Struct_declarator x : p.liststruct_declarator_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Spec_qual */
    public R visit(c.Absyn.TypeSpec p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_specifier_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.QualSpec p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_qualifier_.accept(this, arg), r, arg);
      return r;
    }

/* Struct_declarator */
    public R visit(c.Absyn.Decl p, A arg) {
      R r = leaf(arg);
      r = combine(p.declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Field p, A arg) {
      R r = leaf(arg);
      r = combine(p.constant_expression_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.DecField p, A arg) {
      R r = leaf(arg);
      r = combine(p.declarator_.accept(this, arg), r, arg);
      r = combine(p.constant_expression_.accept(this, arg), r, arg);
      return r;
    }

/* Enum_specifier */
    public R visit(c.Absyn.EnumDec p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Enumerator x : p.listenumerator_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.EnumName p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Enumerator x : p.listenumerator_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.EnumVar p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Enumerator */
    public R visit(c.Absyn.Plain p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.EnumInit p, A arg) {
      R r = leaf(arg);
      r = combine(p.constant_expression_.accept(this, arg), r, arg);
      return r;
    }

/* Declarator */
    public R visit(c.Absyn.BeginPointer p, A arg) {
      R r = leaf(arg);
      r = combine(p.pointer_.accept(this, arg), r, arg);
      r = combine(p.direct_declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.NoPointer p, A arg) {
      R r = leaf(arg);
      r = combine(p.direct_declarator_.accept(this, arg), r, arg);
      return r;
    }

/* Direct_declarator */
    public R visit(c.Absyn.Name p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.ParenDecl p, A arg) {
      R r = leaf(arg);
      r = combine(p.declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.InnitArray p, A arg) {
      R r = leaf(arg);
      r = combine(p.direct_declarator_.accept(this, arg), r, arg);
      r = combine(p.constant_expression_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Incomplete p, A arg) {
      R r = leaf(arg);
      r = combine(p.direct_declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.NewFuncDec p, A arg) {
      R r = leaf(arg);
      r = combine(p.direct_declarator_.accept(this, arg), r, arg);
      r = combine(p.parameter_type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.OldFuncDef p, A arg) {
      R r = leaf(arg);
      r = combine(p.direct_declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.OldFuncDec p, A arg) {
      R r = leaf(arg);
      r = combine(p.direct_declarator_.accept(this, arg), r, arg);
      return r;
    }

/* Pointer */
    public R visit(c.Absyn.Point p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.PointQual p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Type_qualifier x : p.listtype_qualifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.PointPoint p, A arg) {
      R r = leaf(arg);
      r = combine(p.pointer_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.PointQualPoint p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Type_qualifier x : p.listtype_qualifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.pointer_.accept(this, arg), r, arg);
      return r;
    }

/* Parameter_type */
    public R visit(c.Absyn.AllSpec p, A arg) {
      R r = leaf(arg);
      r = combine(p.parameter_declarations_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.More p, A arg) {
      R r = leaf(arg);
      r = combine(p.parameter_declarations_.accept(this, arg), r, arg);
      return r;
    }

/* Parameter_declarations */
    public R visit(c.Absyn.ParamDec p, A arg) {
      R r = leaf(arg);
      r = combine(p.parameter_declaration_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.MoreParamDec p, A arg) {
      R r = leaf(arg);
      r = combine(p.parameter_declarations_.accept(this, arg), r, arg);
      r = combine(p.parameter_declaration_.accept(this, arg), r, arg);
      return r;
    }

/* Parameter_declaration */
    public R visit(c.Absyn.OnlyType p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Declaration_specifier x : p.listdeclaration_specifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.TypeAndParam p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Declaration_specifier x : p.listdeclaration_specifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Abstract p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Declaration_specifier x : p.listdeclaration_specifier_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.abstract_declarator_.accept(this, arg), r, arg);
      return r;
    }

/* Initializer */
    public R visit(c.Absyn.InitExpr p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.InitListOne p, A arg) {
      R r = leaf(arg);
      r = combine(p.initializers_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.InitListTwo p, A arg) {
      R r = leaf(arg);
      r = combine(p.initializers_.accept(this, arg), r, arg);
      return r;
    }

/* Initializers */
    public R visit(c.Absyn.AnInit p, A arg) {
      R r = leaf(arg);
      r = combine(p.initializer_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.MoreInit p, A arg) {
      R r = leaf(arg);
      r = combine(p.initializers_.accept(this, arg), r, arg);
      r = combine(p.initializer_.accept(this, arg), r, arg);
      return r;
    }

/* Type_name */
    public R visit(c.Absyn.PlainType p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Spec_qual x : p.listspec_qual_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.ExtendedType p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Spec_qual x : p.listspec_qual_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.abstract_declarator_.accept(this, arg), r, arg);
      return r;
    }

/* Abstract_declarator */
    public R visit(c.Absyn.PointerStart p, A arg) {
      R r = leaf(arg);
      r = combine(p.pointer_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Advanced p, A arg) {
      R r = leaf(arg);
      r = combine(p.dir_abs_dec_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.PointAdvanced p, A arg) {
      R r = leaf(arg);
      r = combine(p.pointer_.accept(this, arg), r, arg);
      r = combine(p.dir_abs_dec_.accept(this, arg), r, arg);
      return r;
    }

/* Dir_abs_dec */
    public R visit(c.Absyn.WithinParentes p, A arg) {
      R r = leaf(arg);
      r = combine(p.abstract_declarator_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Array p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.InitiatedArray p, A arg) {
      R r = leaf(arg);
      r = combine(p.constant_expression_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.UnInitiated p, A arg) {
      R r = leaf(arg);
      r = combine(p.dir_abs_dec_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Initiated p, A arg) {
      R r = leaf(arg);
      r = combine(p.dir_abs_dec_.accept(this, arg), r, arg);
      r = combine(p.constant_expression_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.OldFunction p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.NewFunction p, A arg) {
      R r = leaf(arg);
      r = combine(p.parameter_type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.OldFuncExpr p, A arg) {
      R r = leaf(arg);
      r = combine(p.dir_abs_dec_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.NewFuncExpr p, A arg) {
      R r = leaf(arg);
      r = combine(p.dir_abs_dec_.accept(this, arg), r, arg);
      r = combine(p.parameter_type_.accept(this, arg), r, arg);
      return r;
    }

/* Stm */
    public R visit(c.Absyn.LabelS p, A arg) {
      R r = leaf(arg);
      r = combine(p.labeled_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.CompS p, A arg) {
      R r = leaf(arg);
      r = combine(p.compound_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.ExprS p, A arg) {
      R r = leaf(arg);
      r = combine(p.expression_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SelS p, A arg) {
      R r = leaf(arg);
      r = combine(p.selection_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.IterS p, A arg) {
      R r = leaf(arg);
      r = combine(p.iter_stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.JumpS p, A arg) {
      R r = leaf(arg);
      r = combine(p.jump_stm_.accept(this, arg), r, arg);
      return r;
    }

/* Labeled_stm */
    public R visit(c.Absyn.SlabelOne p, A arg) {
      R r = leaf(arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SlabelTwo p, A arg) {
      R r = leaf(arg);
      r = combine(p.constant_expression_.accept(this, arg), r, arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SlabelThree p, A arg) {
      R r = leaf(arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }

/* Compound_stm */
    public R visit(c.Absyn.ScompOne p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.ScompTwo p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Stm x : p.liststm_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.ScompThree p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Dec x : p.listdec_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.ScompFour p, A arg) {
      R r = leaf(arg);
      for (c.Absyn.Dec x : p.listdec_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (c.Absyn.Stm x : p.liststm_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Expression_stm */
    public R visit(c.Absyn.SexprOne p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.SexprTwo p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }

/* Selection_stm */
    public R visit(c.Absyn.SselOne p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SselTwo p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      r = combine(p.stm_1.accept(this, arg), r, arg);
      r = combine(p.stm_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SselThree p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }

/* Iter_stm */
    public R visit(c.Absyn.SiterOne p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SiterTwo p, A arg) {
      R r = leaf(arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SiterThree p, A arg) {
      R r = leaf(arg);
      r = combine(p.expression_stm_1.accept(this, arg), r, arg);
      r = combine(p.expression_stm_2.accept(this, arg), r, arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.SiterFour p, A arg) {
      R r = leaf(arg);
      r = combine(p.expression_stm_1.accept(this, arg), r, arg);
      r = combine(p.expression_stm_2.accept(this, arg), r, arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      r = combine(p.stm_.accept(this, arg), r, arg);
      return r;
    }

/* Jump_stm */
    public R visit(c.Absyn.SjumpOne p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.SjumpTwo p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.SjumpThree p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.SjumpFour p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.SjumpFive p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }

/* Exp */
    public R visit(c.Absyn.Ecomma p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eassign p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.assignment_op_.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Econdition p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      r = combine(p.exp_3.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Elor p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eland p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ebitor p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ebitexor p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ebitand p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eeq p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eneq p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Elthen p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Egrthen p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ele p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ege p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eleft p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eright p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eplus p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Eminus p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Etimes p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ediv p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Emod p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Etypeconv p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_name_.accept(this, arg), r, arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Epreinc p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Epredec p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Epreop p, A arg) {
      R r = leaf(arg);
      r = combine(p.unary_operator_.accept(this, arg), r, arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ebytesexpr p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Ebytestype p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_name_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Earray p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_1.accept(this, arg), r, arg);
      r = combine(p.exp_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Efunk p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Efunkpar p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      for (c.Absyn.Exp x : p.listexp_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(c.Absyn.Eselect p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Epoint p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Epostinc p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Epostdec p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Evar p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Econst p, A arg) {
      R r = leaf(arg);
      r = combine(p.constant_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(c.Absyn.Estring p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Constant */
    public R visit(c.Absyn.Efloat p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Echar p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eunsigned p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Elong p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eunsignlong p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Ehexadec p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Ehexaunsign p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Ehexalong p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Ehexaunslong p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eoctal p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eoctalunsign p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eoctallong p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eoctalunslong p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Ecdouble p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Ecfloat p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eclongdouble p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Eint p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Elonger p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Edouble p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Constant_expression */
    public R visit(c.Absyn.Especial p, A arg) {
      R r = leaf(arg);
      r = combine(p.exp_.accept(this, arg), r, arg);
      return r;
    }

/* Unary_operator */
    public R visit(c.Absyn.Address p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Indirection p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Plus p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Negative p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Complement p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.Logicalneg p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Assignment_op */
    public R visit(c.Absyn.Assign p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignMul p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignDiv p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignMod p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignAdd p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignSub p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignLeft p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignRight p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignAnd p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignXor p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(c.Absyn.AssignOr p, A arg) {
      R r = leaf(arg);
      return r;
    }


}
