// File generated by the BNF Converter (bnfc 2.9.5).

package c;

/*** Visitor Design Pattern Skeleton. ***/

/* This implements the common visitor design pattern.
   Tests show it to be slightly less efficient than the
   instanceof method, but easier to use.
   Replace the R and A parameters with the desired return
   and context types.*/

public class VisitSkel
{
  public class ProgramVisitor<R,A> implements c.Absyn.Program.Visitor<R,A>
  {
    public R visit(c.Absyn.Progr p, A arg)
    { /* Code for Progr goes here */
      for (c.Absyn.External_declaration x: p.listexternal_declaration_) {
        x.accept(new External_declarationVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class External_declarationVisitor<R,A> implements c.Absyn.External_declaration.Visitor<R,A>
  {
    public R visit(c.Absyn.Afunc p, A arg)
    { /* Code for Afunc goes here */
      p.function_def_.accept(new Function_defVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Global p, A arg)
    { /* Code for Global goes here */
      p.dec_.accept(new DecVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Function_defVisitor<R,A> implements c.Absyn.Function_def.Visitor<R,A>
  {
    public R visit(c.Absyn.OldFunc p, A arg)
    { /* Code for OldFunc goes here */
      for (c.Absyn.Declaration_specifier x: p.listdeclaration_specifier_) {
        x.accept(new Declaration_specifierVisitor<R,A>(), arg);
      }
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      for (c.Absyn.Dec x: p.listdec_) {
        x.accept(new DecVisitor<R,A>(), arg);
      }
      p.compound_stm_.accept(new Compound_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.NewFunc p, A arg)
    { /* Code for NewFunc goes here */
      for (c.Absyn.Declaration_specifier x: p.listdeclaration_specifier_) {
        x.accept(new Declaration_specifierVisitor<R,A>(), arg);
      }
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      p.compound_stm_.accept(new Compound_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.OldFuncInt p, A arg)
    { /* Code for OldFuncInt goes here */
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      for (c.Absyn.Dec x: p.listdec_) {
        x.accept(new DecVisitor<R,A>(), arg);
      }
      p.compound_stm_.accept(new Compound_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.NewFuncInt p, A arg)
    { /* Code for NewFuncInt goes here */
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      p.compound_stm_.accept(new Compound_stmVisitor<R,A>(), arg);
      return null;
    }
  }
  public class DecVisitor<R,A> implements c.Absyn.Dec.Visitor<R,A>
  {
    public R visit(c.Absyn.NoDeclarator p, A arg)
    { /* Code for NoDeclarator goes here */
      for (c.Absyn.Declaration_specifier x: p.listdeclaration_specifier_) {
        x.accept(new Declaration_specifierVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.Declarators p, A arg)
    { /* Code for Declarators goes here */
      for (c.Absyn.Declaration_specifier x: p.listdeclaration_specifier_) {
        x.accept(new Declaration_specifierVisitor<R,A>(), arg);
      }
      for (c.Absyn.Init_declarator x: p.listinit_declarator_) {
        x.accept(new Init_declaratorVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class Declaration_specifierVisitor<R,A> implements c.Absyn.Declaration_specifier.Visitor<R,A>
  {
    public R visit(c.Absyn.Type p, A arg)
    { /* Code for Type goes here */
      p.type_specifier_.accept(new Type_specifierVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Storage p, A arg)
    { /* Code for Storage goes here */
      p.storage_class_specifier_.accept(new Storage_class_specifierVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SpecProp p, A arg)
    { /* Code for SpecProp goes here */
      p.type_qualifier_.accept(new Type_qualifierVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Init_declaratorVisitor<R,A> implements c.Absyn.Init_declarator.Visitor<R,A>
  {
    public R visit(c.Absyn.OnlyDecl p, A arg)
    { /* Code for OnlyDecl goes here */
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.InitDecl p, A arg)
    { /* Code for InitDecl goes here */
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      p.initializer_.accept(new InitializerVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Type_specifierVisitor<R,A> implements c.Absyn.Type_specifier.Visitor<R,A>
  {
    public R visit(c.Absyn.Tvoid p, A arg)
    { /* Code for Tvoid goes here */
      return null;
    }
    public R visit(c.Absyn.Tchar p, A arg)
    { /* Code for Tchar goes here */
      return null;
    }
    public R visit(c.Absyn.Tshort p, A arg)
    { /* Code for Tshort goes here */
      return null;
    }
    public R visit(c.Absyn.Tint p, A arg)
    { /* Code for Tint goes here */
      return null;
    }
    public R visit(c.Absyn.Tlong p, A arg)
    { /* Code for Tlong goes here */
      return null;
    }
    public R visit(c.Absyn.Tfloat p, A arg)
    { /* Code for Tfloat goes here */
      return null;
    }
    public R visit(c.Absyn.Tdouble p, A arg)
    { /* Code for Tdouble goes here */
      return null;
    }
    public R visit(c.Absyn.Tsigned p, A arg)
    { /* Code for Tsigned goes here */
      return null;
    }
    public R visit(c.Absyn.Tunsigned p, A arg)
    { /* Code for Tunsigned goes here */
      return null;
    }
    public R visit(c.Absyn.Tstruct p, A arg)
    { /* Code for Tstruct goes here */
      p.struct_or_union_spec_.accept(new Struct_or_union_specVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Tenum p, A arg)
    { /* Code for Tenum goes here */
      p.enum_specifier_.accept(new Enum_specifierVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Tname p, A arg)
    { /* Code for Tname goes here */
      return null;
    }
  }
  public class Storage_class_specifierVisitor<R,A> implements c.Absyn.Storage_class_specifier.Visitor<R,A>
  {
    public R visit(c.Absyn.MyType p, A arg)
    { /* Code for MyType goes here */
      return null;
    }
    public R visit(c.Absyn.GlobalPrograms p, A arg)
    { /* Code for GlobalPrograms goes here */
      return null;
    }
    public R visit(c.Absyn.LocalProgram p, A arg)
    { /* Code for LocalProgram goes here */
      return null;
    }
    public R visit(c.Absyn.LocalBlock p, A arg)
    { /* Code for LocalBlock goes here */
      return null;
    }
    public R visit(c.Absyn.LocalReg p, A arg)
    { /* Code for LocalReg goes here */
      return null;
    }
  }
  public class Type_qualifierVisitor<R,A> implements c.Absyn.Type_qualifier.Visitor<R,A>
  {
    public R visit(c.Absyn.Const p, A arg)
    { /* Code for Const goes here */
      return null;
    }
    public R visit(c.Absyn.NoOptim p, A arg)
    { /* Code for NoOptim goes here */
      return null;
    }
  }
  public class Struct_or_union_specVisitor<R,A> implements c.Absyn.Struct_or_union_spec.Visitor<R,A>
  {
    public R visit(c.Absyn.Tag p, A arg)
    { /* Code for Tag goes here */
      p.struct_or_union_.accept(new Struct_or_unionVisitor<R,A>(), arg);
      //p.ident_;
      for (c.Absyn.Struct_dec x: p.liststruct_dec_) {
        x.accept(new Struct_decVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.Unique p, A arg)
    { /* Code for Unique goes here */
      p.struct_or_union_.accept(new Struct_or_unionVisitor<R,A>(), arg);
      for (c.Absyn.Struct_dec x: p.liststruct_dec_) {
        x.accept(new Struct_decVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.TagType p, A arg)
    { /* Code for TagType goes here */
      p.struct_or_union_.accept(new Struct_or_unionVisitor<R,A>(), arg);
      //p.ident_;
      return null;
    }
  }
  public class Struct_or_unionVisitor<R,A> implements c.Absyn.Struct_or_union.Visitor<R,A>
  {
    public R visit(c.Absyn.Struct p, A arg)
    { /* Code for Struct goes here */
      return null;
    }
    public R visit(c.Absyn.Union p, A arg)
    { /* Code for Union goes here */
      return null;
    }
  }
  public class Struct_decVisitor<R,A> implements c.Absyn.Struct_dec.Visitor<R,A>
  {
    public R visit(c.Absyn.Structen p, A arg)
    { /* Code for Structen goes here */
      for (c.Absyn.Spec_qual x: p.listspec_qual_) {
        x.accept(new Spec_qualVisitor<R,A>(), arg);
      }
      for (c.Absyn.Struct_declarator x: p.liststruct_declarator_) {
        x.accept(new Struct_declaratorVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class Spec_qualVisitor<R,A> implements c.Absyn.Spec_qual.Visitor<R,A>
  {
    public R visit(c.Absyn.TypeSpec p, A arg)
    { /* Code for TypeSpec goes here */
      p.type_specifier_.accept(new Type_specifierVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.QualSpec p, A arg)
    { /* Code for QualSpec goes here */
      p.type_qualifier_.accept(new Type_qualifierVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Struct_declaratorVisitor<R,A> implements c.Absyn.Struct_declarator.Visitor<R,A>
  {
    public R visit(c.Absyn.Decl p, A arg)
    { /* Code for Decl goes here */
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Field p, A arg)
    { /* Code for Field goes here */
      p.constant_expression_.accept(new Constant_expressionVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.DecField p, A arg)
    { /* Code for DecField goes here */
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      p.constant_expression_.accept(new Constant_expressionVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Enum_specifierVisitor<R,A> implements c.Absyn.Enum_specifier.Visitor<R,A>
  {
    public R visit(c.Absyn.EnumDec p, A arg)
    { /* Code for EnumDec goes here */
      for (c.Absyn.Enumerator x: p.listenumerator_) {
        x.accept(new EnumeratorVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.EnumName p, A arg)
    { /* Code for EnumName goes here */
      //p.ident_;
      for (c.Absyn.Enumerator x: p.listenumerator_) {
        x.accept(new EnumeratorVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.EnumVar p, A arg)
    { /* Code for EnumVar goes here */
      //p.ident_;
      return null;
    }
  }
  public class EnumeratorVisitor<R,A> implements c.Absyn.Enumerator.Visitor<R,A>
  {
    public R visit(c.Absyn.Plain p, A arg)
    { /* Code for Plain goes here */
      //p.ident_;
      return null;
    }
    public R visit(c.Absyn.EnumInit p, A arg)
    { /* Code for EnumInit goes here */
      //p.ident_;
      p.constant_expression_.accept(new Constant_expressionVisitor<R,A>(), arg);
      return null;
    }
  }
  public class DeclaratorVisitor<R,A> implements c.Absyn.Declarator.Visitor<R,A>
  {
    public R visit(c.Absyn.BeginPointer p, A arg)
    { /* Code for BeginPointer goes here */
      p.pointer_.accept(new PointerVisitor<R,A>(), arg);
      p.direct_declarator_.accept(new Direct_declaratorVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.NoPointer p, A arg)
    { /* Code for NoPointer goes here */
      p.direct_declarator_.accept(new Direct_declaratorVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Direct_declaratorVisitor<R,A> implements c.Absyn.Direct_declarator.Visitor<R,A>
  {
    public R visit(c.Absyn.Name p, A arg)
    { /* Code for Name goes here */
      //p.ident_;
      return null;
    }
    public R visit(c.Absyn.ParenDecl p, A arg)
    { /* Code for ParenDecl goes here */
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.InnitArray p, A arg)
    { /* Code for InnitArray goes here */
      p.direct_declarator_.accept(new Direct_declaratorVisitor<R,A>(), arg);
      p.constant_expression_.accept(new Constant_expressionVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Incomplete p, A arg)
    { /* Code for Incomplete goes here */
      p.direct_declarator_.accept(new Direct_declaratorVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.NewFuncDec p, A arg)
    { /* Code for NewFuncDec goes here */
      p.direct_declarator_.accept(new Direct_declaratorVisitor<R,A>(), arg);
      p.parameter_type_.accept(new Parameter_typeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.OldFuncDef p, A arg)
    { /* Code for OldFuncDef goes here */
      p.direct_declarator_.accept(new Direct_declaratorVisitor<R,A>(), arg);
      for (String x: p.listident_) {
        //x;
      }
      return null;
    }
    public R visit(c.Absyn.OldFuncDec p, A arg)
    { /* Code for OldFuncDec goes here */
      p.direct_declarator_.accept(new Direct_declaratorVisitor<R,A>(), arg);
      return null;
    }
  }
  public class PointerVisitor<R,A> implements c.Absyn.Pointer.Visitor<R,A>
  {
    public R visit(c.Absyn.Point p, A arg)
    { /* Code for Point goes here */
      return null;
    }
    public R visit(c.Absyn.PointQual p, A arg)
    { /* Code for PointQual goes here */
      for (c.Absyn.Type_qualifier x: p.listtype_qualifier_) {
        x.accept(new Type_qualifierVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.PointPoint p, A arg)
    { /* Code for PointPoint goes here */
      p.pointer_.accept(new PointerVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.PointQualPoint p, A arg)
    { /* Code for PointQualPoint goes here */
      for (c.Absyn.Type_qualifier x: p.listtype_qualifier_) {
        x.accept(new Type_qualifierVisitor<R,A>(), arg);
      }
      p.pointer_.accept(new PointerVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Parameter_typeVisitor<R,A> implements c.Absyn.Parameter_type.Visitor<R,A>
  {
    public R visit(c.Absyn.AllSpec p, A arg)
    { /* Code for AllSpec goes here */
      p.parameter_declarations_.accept(new Parameter_declarationsVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.More p, A arg)
    { /* Code for More goes here */
      p.parameter_declarations_.accept(new Parameter_declarationsVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Parameter_declarationsVisitor<R,A> implements c.Absyn.Parameter_declarations.Visitor<R,A>
  {
    public R visit(c.Absyn.ParamDec p, A arg)
    { /* Code for ParamDec goes here */
      p.parameter_declaration_.accept(new Parameter_declarationVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.MoreParamDec p, A arg)
    { /* Code for MoreParamDec goes here */
      p.parameter_declarations_.accept(new Parameter_declarationsVisitor<R,A>(), arg);
      p.parameter_declaration_.accept(new Parameter_declarationVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Parameter_declarationVisitor<R,A> implements c.Absyn.Parameter_declaration.Visitor<R,A>
  {
    public R visit(c.Absyn.OnlyType p, A arg)
    { /* Code for OnlyType goes here */
      for (c.Absyn.Declaration_specifier x: p.listdeclaration_specifier_) {
        x.accept(new Declaration_specifierVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.TypeAndParam p, A arg)
    { /* Code for TypeAndParam goes here */
      for (c.Absyn.Declaration_specifier x: p.listdeclaration_specifier_) {
        x.accept(new Declaration_specifierVisitor<R,A>(), arg);
      }
      p.declarator_.accept(new DeclaratorVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Abstract p, A arg)
    { /* Code for Abstract goes here */
      for (c.Absyn.Declaration_specifier x: p.listdeclaration_specifier_) {
        x.accept(new Declaration_specifierVisitor<R,A>(), arg);
      }
      p.abstract_declarator_.accept(new Abstract_declaratorVisitor<R,A>(), arg);
      return null;
    }
  }
  public class InitializerVisitor<R,A> implements c.Absyn.Initializer.Visitor<R,A>
  {
    public R visit(c.Absyn.InitExpr p, A arg)
    { /* Code for InitExpr goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.InitListOne p, A arg)
    { /* Code for InitListOne goes here */
      p.initializers_.accept(new InitializersVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.InitListTwo p, A arg)
    { /* Code for InitListTwo goes here */
      p.initializers_.accept(new InitializersVisitor<R,A>(), arg);
      return null;
    }
  }
  public class InitializersVisitor<R,A> implements c.Absyn.Initializers.Visitor<R,A>
  {
    public R visit(c.Absyn.AnInit p, A arg)
    { /* Code for AnInit goes here */
      p.initializer_.accept(new InitializerVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.MoreInit p, A arg)
    { /* Code for MoreInit goes here */
      p.initializers_.accept(new InitializersVisitor<R,A>(), arg);
      p.initializer_.accept(new InitializerVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Type_nameVisitor<R,A> implements c.Absyn.Type_name.Visitor<R,A>
  {
    public R visit(c.Absyn.PlainType p, A arg)
    { /* Code for PlainType goes here */
      for (c.Absyn.Spec_qual x: p.listspec_qual_) {
        x.accept(new Spec_qualVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.ExtendedType p, A arg)
    { /* Code for ExtendedType goes here */
      for (c.Absyn.Spec_qual x: p.listspec_qual_) {
        x.accept(new Spec_qualVisitor<R,A>(), arg);
      }
      p.abstract_declarator_.accept(new Abstract_declaratorVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Abstract_declaratorVisitor<R,A> implements c.Absyn.Abstract_declarator.Visitor<R,A>
  {
    public R visit(c.Absyn.PointerStart p, A arg)
    { /* Code for PointerStart goes here */
      p.pointer_.accept(new PointerVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Advanced p, A arg)
    { /* Code for Advanced goes here */
      p.dir_abs_dec_.accept(new Dir_abs_decVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.PointAdvanced p, A arg)
    { /* Code for PointAdvanced goes here */
      p.pointer_.accept(new PointerVisitor<R,A>(), arg);
      p.dir_abs_dec_.accept(new Dir_abs_decVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Dir_abs_decVisitor<R,A> implements c.Absyn.Dir_abs_dec.Visitor<R,A>
  {
    public R visit(c.Absyn.WithinParentes p, A arg)
    { /* Code for WithinParentes goes here */
      p.abstract_declarator_.accept(new Abstract_declaratorVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Array p, A arg)
    { /* Code for Array goes here */
      return null;
    }
    public R visit(c.Absyn.InitiatedArray p, A arg)
    { /* Code for InitiatedArray goes here */
      p.constant_expression_.accept(new Constant_expressionVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.UnInitiated p, A arg)
    { /* Code for UnInitiated goes here */
      p.dir_abs_dec_.accept(new Dir_abs_decVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Initiated p, A arg)
    { /* Code for Initiated goes here */
      p.dir_abs_dec_.accept(new Dir_abs_decVisitor<R,A>(), arg);
      p.constant_expression_.accept(new Constant_expressionVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.OldFunction p, A arg)
    { /* Code for OldFunction goes here */
      return null;
    }
    public R visit(c.Absyn.NewFunction p, A arg)
    { /* Code for NewFunction goes here */
      p.parameter_type_.accept(new Parameter_typeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.OldFuncExpr p, A arg)
    { /* Code for OldFuncExpr goes here */
      p.dir_abs_dec_.accept(new Dir_abs_decVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.NewFuncExpr p, A arg)
    { /* Code for NewFuncExpr goes here */
      p.dir_abs_dec_.accept(new Dir_abs_decVisitor<R,A>(), arg);
      p.parameter_type_.accept(new Parameter_typeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class StmVisitor<R,A> implements c.Absyn.Stm.Visitor<R,A>
  {
    public R visit(c.Absyn.LabelS p, A arg)
    { /* Code for LabelS goes here */
      p.labeled_stm_.accept(new Labeled_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.CompS p, A arg)
    { /* Code for CompS goes here */
      p.compound_stm_.accept(new Compound_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.ExprS p, A arg)
    { /* Code for ExprS goes here */
      p.expression_stm_.accept(new Expression_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SelS p, A arg)
    { /* Code for SelS goes here */
      p.selection_stm_.accept(new Selection_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.IterS p, A arg)
    { /* Code for IterS goes here */
      p.iter_stm_.accept(new Iter_stmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.JumpS p, A arg)
    { /* Code for JumpS goes here */
      p.jump_stm_.accept(new Jump_stmVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Labeled_stmVisitor<R,A> implements c.Absyn.Labeled_stm.Visitor<R,A>
  {
    public R visit(c.Absyn.SlabelOne p, A arg)
    { /* Code for SlabelOne goes here */
      //p.ident_;
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SlabelTwo p, A arg)
    { /* Code for SlabelTwo goes here */
      p.constant_expression_.accept(new Constant_expressionVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SlabelThree p, A arg)
    { /* Code for SlabelThree goes here */
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Compound_stmVisitor<R,A> implements c.Absyn.Compound_stm.Visitor<R,A>
  {
    public R visit(c.Absyn.ScompOne p, A arg)
    { /* Code for ScompOne goes here */
      return null;
    }
    public R visit(c.Absyn.ScompTwo p, A arg)
    { /* Code for ScompTwo goes here */
      for (c.Absyn.Stm x: p.liststm_) {
        x.accept(new StmVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.ScompThree p, A arg)
    { /* Code for ScompThree goes here */
      for (c.Absyn.Dec x: p.listdec_) {
        x.accept(new DecVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.ScompFour p, A arg)
    { /* Code for ScompFour goes here */
      for (c.Absyn.Dec x: p.listdec_) {
        x.accept(new DecVisitor<R,A>(), arg);
      }
      for (c.Absyn.Stm x: p.liststm_) {
        x.accept(new StmVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class Expression_stmVisitor<R,A> implements c.Absyn.Expression_stm.Visitor<R,A>
  {
    public R visit(c.Absyn.SexprOne p, A arg)
    { /* Code for SexprOne goes here */
      return null;
    }
    public R visit(c.Absyn.SexprTwo p, A arg)
    { /* Code for SexprTwo goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Selection_stmVisitor<R,A> implements c.Absyn.Selection_stm.Visitor<R,A>
  {
    public R visit(c.Absyn.SselOne p, A arg)
    { /* Code for SselOne goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SselTwo p, A arg)
    { /* Code for SselTwo goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      p.stm_1.accept(new StmVisitor<R,A>(), arg);
      p.stm_2.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SselThree p, A arg)
    { /* Code for SselThree goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Iter_stmVisitor<R,A> implements c.Absyn.Iter_stm.Visitor<R,A>
  {
    public R visit(c.Absyn.SiterOne p, A arg)
    { /* Code for SiterOne goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SiterTwo p, A arg)
    { /* Code for SiterTwo goes here */
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SiterThree p, A arg)
    { /* Code for SiterThree goes here */
      p.expression_stm_1.accept(new Expression_stmVisitor<R,A>(), arg);
      p.expression_stm_2.accept(new Expression_stmVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.SiterFour p, A arg)
    { /* Code for SiterFour goes here */
      p.expression_stm_1.accept(new Expression_stmVisitor<R,A>(), arg);
      p.expression_stm_2.accept(new Expression_stmVisitor<R,A>(), arg);
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      p.stm_.accept(new StmVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Jump_stmVisitor<R,A> implements c.Absyn.Jump_stm.Visitor<R,A>
  {
    public R visit(c.Absyn.SjumpOne p, A arg)
    { /* Code for SjumpOne goes here */
      //p.ident_;
      return null;
    }
    public R visit(c.Absyn.SjumpTwo p, A arg)
    { /* Code for SjumpTwo goes here */
      return null;
    }
    public R visit(c.Absyn.SjumpThree p, A arg)
    { /* Code for SjumpThree goes here */
      return null;
    }
    public R visit(c.Absyn.SjumpFour p, A arg)
    { /* Code for SjumpFour goes here */
      return null;
    }
    public R visit(c.Absyn.SjumpFive p, A arg)
    { /* Code for SjumpFive goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
  }
  public class ExpVisitor<R,A> implements c.Absyn.Exp.Visitor<R,A>
  {
    public R visit(c.Absyn.Ecomma p, A arg)
    { /* Code for Ecomma goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eassign p, A arg)
    { /* Code for Eassign goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.assignment_op_.accept(new Assignment_opVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Econdition p, A arg)
    { /* Code for Econdition goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      p.exp_3.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Elor p, A arg)
    { /* Code for Elor goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eland p, A arg)
    { /* Code for Eland goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ebitor p, A arg)
    { /* Code for Ebitor goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ebitexor p, A arg)
    { /* Code for Ebitexor goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ebitand p, A arg)
    { /* Code for Ebitand goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eeq p, A arg)
    { /* Code for Eeq goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eneq p, A arg)
    { /* Code for Eneq goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Elthen p, A arg)
    { /* Code for Elthen goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Egrthen p, A arg)
    { /* Code for Egrthen goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ele p, A arg)
    { /* Code for Ele goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ege p, A arg)
    { /* Code for Ege goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eleft p, A arg)
    { /* Code for Eleft goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eright p, A arg)
    { /* Code for Eright goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eplus p, A arg)
    { /* Code for Eplus goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Eminus p, A arg)
    { /* Code for Eminus goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Etimes p, A arg)
    { /* Code for Etimes goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ediv p, A arg)
    { /* Code for Ediv goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Emod p, A arg)
    { /* Code for Emod goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Etypeconv p, A arg)
    { /* Code for Etypeconv goes here */
      p.type_name_.accept(new Type_nameVisitor<R,A>(), arg);
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Epreinc p, A arg)
    { /* Code for Epreinc goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Epredec p, A arg)
    { /* Code for Epredec goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Epreop p, A arg)
    { /* Code for Epreop goes here */
      p.unary_operator_.accept(new Unary_operatorVisitor<R,A>(), arg);
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ebytesexpr p, A arg)
    { /* Code for Ebytesexpr goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Ebytestype p, A arg)
    { /* Code for Ebytestype goes here */
      p.type_name_.accept(new Type_nameVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Earray p, A arg)
    { /* Code for Earray goes here */
      p.exp_1.accept(new ExpVisitor<R,A>(), arg);
      p.exp_2.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Efunk p, A arg)
    { /* Code for Efunk goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Efunkpar p, A arg)
    { /* Code for Efunkpar goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      for (c.Absyn.Exp x: p.listexp_) {
        x.accept(new ExpVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(c.Absyn.Eselect p, A arg)
    { /* Code for Eselect goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      //p.ident_;
      return null;
    }
    public R visit(c.Absyn.Epoint p, A arg)
    { /* Code for Epoint goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      //p.ident_;
      return null;
    }
    public R visit(c.Absyn.Epostinc p, A arg)
    { /* Code for Epostinc goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Epostdec p, A arg)
    { /* Code for Epostdec goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Evar p, A arg)
    { /* Code for Evar goes here */
      //p.ident_;
      return null;
    }
    public R visit(c.Absyn.Econst p, A arg)
    { /* Code for Econst goes here */
      p.constant_.accept(new ConstantVisitor<R,A>(), arg);
      return null;
    }
    public R visit(c.Absyn.Estring p, A arg)
    { /* Code for Estring goes here */
      //p.string_;
      return null;
    }
  }
  public class ConstantVisitor<R,A> implements c.Absyn.Constant.Visitor<R,A>
  {
    public R visit(c.Absyn.Efloat p, A arg)
    { /* Code for Efloat goes here */
      //p.double_;
      return null;
    }
    public R visit(c.Absyn.Echar p, A arg)
    { /* Code for Echar goes here */
      //p.char_;
      return null;
    }
    public R visit(c.Absyn.Eunsigned p, A arg)
    { /* Code for Eunsigned goes here */
      //p.unsigned_;
      return null;
    }
    public R visit(c.Absyn.Elong p, A arg)
    { /* Code for Elong goes here */
      //p.long_;
      return null;
    }
    public R visit(c.Absyn.Eunsignlong p, A arg)
    { /* Code for Eunsignlong goes here */
      //p.unsignedlong_;
      return null;
    }
    public R visit(c.Absyn.Ehexadec p, A arg)
    { /* Code for Ehexadec goes here */
      //p.hexadecimal_;
      return null;
    }
    public R visit(c.Absyn.Ehexaunsign p, A arg)
    { /* Code for Ehexaunsign goes here */
      //p.hexunsigned_;
      return null;
    }
    public R visit(c.Absyn.Ehexalong p, A arg)
    { /* Code for Ehexalong goes here */
      //p.hexlong_;
      return null;
    }
    public R visit(c.Absyn.Ehexaunslong p, A arg)
    { /* Code for Ehexaunslong goes here */
      //p.hexunslong_;
      return null;
    }
    public R visit(c.Absyn.Eoctal p, A arg)
    { /* Code for Eoctal goes here */
      //p.octal_;
      return null;
    }
    public R visit(c.Absyn.Eoctalunsign p, A arg)
    { /* Code for Eoctalunsign goes here */
      //p.octalunsigned_;
      return null;
    }
    public R visit(c.Absyn.Eoctallong p, A arg)
    { /* Code for Eoctallong goes here */
      //p.octallong_;
      return null;
    }
    public R visit(c.Absyn.Eoctalunslong p, A arg)
    { /* Code for Eoctalunslong goes here */
      //p.octalunslong_;
      return null;
    }
    public R visit(c.Absyn.Ecdouble p, A arg)
    { /* Code for Ecdouble goes here */
      //p.cdouble_;
      return null;
    }
    public R visit(c.Absyn.Ecfloat p, A arg)
    { /* Code for Ecfloat goes here */
      //p.cfloat_;
      return null;
    }
    public R visit(c.Absyn.Eclongdouble p, A arg)
    { /* Code for Eclongdouble goes here */
      //p.clongdouble_;
      return null;
    }
    public R visit(c.Absyn.Eint p, A arg)
    { /* Code for Eint goes here */
      //p.integer_;
      return null;
    }
    public R visit(c.Absyn.Elonger p, A arg)
    { /* Code for Elonger goes here */
      //p.integer_;
      return null;
    }
    public R visit(c.Absyn.Edouble p, A arg)
    { /* Code for Edouble goes here */
      //p.double_;
      return null;
    }
  }
  public class Constant_expressionVisitor<R,A> implements c.Absyn.Constant_expression.Visitor<R,A>
  {
    public R visit(c.Absyn.Especial p, A arg)
    { /* Code for Especial goes here */
      p.exp_.accept(new ExpVisitor<R,A>(), arg);
      return null;
    }
  }
  public class Unary_operatorVisitor<R,A> implements c.Absyn.Unary_operator.Visitor<R,A>
  {
    public R visit(c.Absyn.Address p, A arg)
    { /* Code for Address goes here */
      return null;
    }
    public R visit(c.Absyn.Indirection p, A arg)
    { /* Code for Indirection goes here */
      return null;
    }
    public R visit(c.Absyn.Plus p, A arg)
    { /* Code for Plus goes here */
      return null;
    }
    public R visit(c.Absyn.Negative p, A arg)
    { /* Code for Negative goes here */
      return null;
    }
    public R visit(c.Absyn.Complement p, A arg)
    { /* Code for Complement goes here */
      return null;
    }
    public R visit(c.Absyn.Logicalneg p, A arg)
    { /* Code for Logicalneg goes here */
      return null;
    }
  }
  public class Assignment_opVisitor<R,A> implements c.Absyn.Assignment_op.Visitor<R,A>
  {
    public R visit(c.Absyn.Assign p, A arg)
    { /* Code for Assign goes here */
      return null;
    }
    public R visit(c.Absyn.AssignMul p, A arg)
    { /* Code for AssignMul goes here */
      return null;
    }
    public R visit(c.Absyn.AssignDiv p, A arg)
    { /* Code for AssignDiv goes here */
      return null;
    }
    public R visit(c.Absyn.AssignMod p, A arg)
    { /* Code for AssignMod goes here */
      return null;
    }
    public R visit(c.Absyn.AssignAdd p, A arg)
    { /* Code for AssignAdd goes here */
      return null;
    }
    public R visit(c.Absyn.AssignSub p, A arg)
    { /* Code for AssignSub goes here */
      return null;
    }
    public R visit(c.Absyn.AssignLeft p, A arg)
    { /* Code for AssignLeft goes here */
      return null;
    }
    public R visit(c.Absyn.AssignRight p, A arg)
    { /* Code for AssignRight goes here */
      return null;
    }
    public R visit(c.Absyn.AssignAnd p, A arg)
    { /* Code for AssignAnd goes here */
      return null;
    }
    public R visit(c.Absyn.AssignXor p, A arg)
    { /* Code for AssignXor goes here */
      return null;
    }
    public R visit(c.Absyn.AssignOr p, A arg)
    { /* Code for AssignOr goes here */
      return null;
    }
  }
}
