// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Afunc  extends External_declaration {
  public final Function_def function_def_;
  public Afunc(Function_def p1) { function_def_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Afunc) {
      Afunc x = (Afunc)o;
      return this.function_def_.equals(x.function_def_);
    }
    return false;
  }

  public int hashCode() {
    return this.function_def_.hashCode();
  }


}
