// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class AllSpec  extends Parameter_type {
  public final Parameter_declarations parameter_declarations_;
  public AllSpec(Parameter_declarations p1) { parameter_declarations_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof AllSpec) {
      AllSpec x = (AllSpec)o;
      return this.parameter_declarations_.equals(x.parameter_declarations_);
    }
    return false;
  }

  public int hashCode() {
    return this.parameter_declarations_.hashCode();
  }


}
