// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class AnInit  extends Initializers {
  public final Initializer initializer_;
  public AnInit(Initializer p1) { initializer_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof AnInit) {
      AnInit x = (AnInit)o;
      return this.initializer_.equals(x.initializer_);
    }
    return false;
  }

  public int hashCode() {
    return this.initializer_.hashCode();
  }


}
