// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Assign  extends Assignment_op {
  public Assign() { }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Assign) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
