// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

import c.InternalTypeRepresentation;

public abstract class Assignment_op implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Assign p, A arg);
    public R visit(AssignMul p, A arg);
    public R visit(AssignDiv p, A arg);
    public R visit(AssignMod p, A arg);
    public R visit(AssignAdd p, A arg);
    public R visit(AssignSub p, A arg);
    public R visit(AssignLeft p, A arg);
    public R visit(AssignRight p, A arg);
    public R visit(AssignAnd p, A arg);
    public R visit(AssignXor p, A arg);
    public R visit(AssignOr p, A arg);

  }

}
