// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Constant implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Efloat p, A arg);
    public R visit(Echar p, A arg);
    public R visit(Eunsigned p, A arg);
    public R visit(Elong p, A arg);
    public R visit(Eunsignlong p, A arg);
    public R visit(Ehexadec p, A arg);
    public R visit(Ehexaunsign p, A arg);
    public R visit(Ehexalong p, A arg);
    public R visit(Ehexaunslong p, A arg);
    public R visit(Eoctal p, A arg);
    public R visit(Eoctalunsign p, A arg);
    public R visit(Eoctallong p, A arg);
    public R visit(Eoctalunslong p, A arg);
    public R visit(Ecdouble p, A arg);
    public R visit(Ecfloat p, A arg);
    public R visit(Eclongdouble p, A arg);
    public R visit(Eint p, A arg);
    public R visit(Elonger p, A arg);
    public R visit(Edouble p, A arg);

  }

}
