// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Dec implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(NoDeclarator p, A arg);
    public R visit(Declarators p, A arg);

  }

}
