// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class DecField  extends Struct_declarator {
  public final Declarator declarator_;
  public final Constant_expression constant_expression_;
  public DecField(Declarator p1, Constant_expression p2) { declarator_ = p1; constant_expression_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof DecField) {
      DecField x = (DecField)o;
      return this.declarator_.equals(x.declarator_) && this.constant_expression_.equals(x.constant_expression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.declarator_.hashCode())+this.constant_expression_.hashCode();
  }


}
