// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Declarators  extends Dec {
  public final ListDeclaration_specifier listdeclaration_specifier_;
  public final ListInit_declarator listinit_declarator_;
  public Declarators(ListDeclaration_specifier p1, ListInit_declarator p2) { listdeclaration_specifier_ = p1; listinit_declarator_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Declarators) {
      Declarators x = (Declarators)o;
      return this.listdeclaration_specifier_.equals(x.listdeclaration_specifier_) && this.listinit_declarator_.equals(x.listinit_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listdeclaration_specifier_.hashCode())+this.listinit_declarator_.hashCode();
  }


}
