// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Decl  extends Struct_declarator {
  public final Declarator declarator_;
  public Decl(Declarator p1) { declarator_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Decl) {
      Decl x = (Decl)o;
      return this.declarator_.equals(x.declarator_);
    }
    return false;
  }

  public int hashCode() {
    return this.declarator_.hashCode();
  }


}
