// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Direct_declarator implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Name p, A arg);
    public R visit(ParenDecl p, A arg);
    public R visit(InnitArray p, A arg);
    public R visit(Incomplete p, A arg);
    public R visit(NewFuncDec p, A arg);
    public R visit(OldFuncDef p, A arg);
    public R visit(OldFuncDec p, A arg);

  }

}
