// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Eassign  extends Exp {
  public final Exp exp_1, exp_2;
  public final Assignment_op assignment_op_;
  public Eassign(Exp p1, Assignment_op p2, Exp p3) { exp_1 = p1; assignment_op_ = p2; exp_2 = p3; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Eassign) {
      Eassign x = (Eassign)o;
      return this.exp_1.equals(x.exp_1) && this.assignment_op_.equals(x.assignment_op_) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_1.hashCode())+this.assignment_op_.hashCode())+this.exp_2.hashCode();
  }


}
