// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Ebytestype  extends Exp {
  public final Type_name type_name_;
  public Ebytestype(Type_name p1) { type_name_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ebytestype) {
      Ebytestype x = (Ebytestype)o;
      return this.type_name_.equals(x.type_name_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_name_.hashCode();
  }


}
