// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Ecdouble  extends Constant {
  public final String cdouble_;
  public Ecdouble(String p1) { cdouble_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ecdouble) {
      Ecdouble x = (Ecdouble)o;
      return this.cdouble_.equals(x.cdouble_);
    }
    return false;
  }

  public int hashCode() {
    return this.cdouble_.hashCode();
  }


}
