// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Ecfloat  extends Constant {
  public final String cfloat_;
  public Ecfloat(String p1) { cfloat_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ecfloat) {
      Ecfloat x = (Ecfloat)o;
      return this.cfloat_.equals(x.cfloat_);
    }
    return false;
  }

  public int hashCode() {
    return this.cfloat_.hashCode();
  }


}
