// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Echar  extends Constant {
  public final Character char_;
  public Echar(Character p1) { char_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Echar) {
      Echar x = (Echar)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
