// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

import c.InternalTypeRepresentation;

public class Econst  extends Exp {
  public final Constant constant_;
  public Econst(Constant p1, InternalTypeRepresentation type) {super(type); constant_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Econst) {
      Econst x = (Econst)o;
      return this.constant_.equals(x.constant_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_.hashCode();
  }


}
