// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Efunk  extends Exp {
  public final Exp exp_;
  public Efunk(Exp p1) { exp_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Efunk) {
      Efunk x = (Efunk)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
