// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Ehexalong  extends Constant {
  public final String hexlong_;
  public Ehexalong(String p1) { hexlong_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ehexalong) {
      Ehexalong x = (Ehexalong)o;
      return this.hexlong_.equals(x.hexlong_);
    }
    return false;
  }

  public int hashCode() {
    return this.hexlong_.hashCode();
  }


}
