// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Ehexaunsign  extends Constant {
  public final String hexunsigned_;
  public Ehexaunsign(String p1) { hexunsigned_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Ehexaunsign) {
      Ehexaunsign x = (Ehexaunsign)o;
      return this.hexunsigned_.equals(x.hexunsigned_);
    }
    return false;
  }

  public int hashCode() {
    return this.hexunsigned_.hashCode();
  }


}
