// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Eint  extends Constant {
  public final Integer integer_;
  public Eint(Integer p1) { integer_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Eint) {
      Eint x = (Eint)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
