// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Elonger  extends Constant {
  public final Integer integer_;
  public Elonger(Integer p1) { integer_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Elonger) {
      Elonger x = (Elonger)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
