// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class EnumDec  extends Enum_specifier {
  public final ListEnumerator listenumerator_;
  public EnumDec(ListEnumerator p1) { listenumerator_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof EnumDec) {
      EnumDec x = (EnumDec)o;
      return this.listenumerator_.equals(x.listenumerator_);
    }
    return false;
  }

  public int hashCode() {
    return this.listenumerator_.hashCode();
  }


}
