// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class EnumInit  extends Enumerator {
  public final String ident_;
  public final Constant_expression constant_expression_;
  public EnumInit(String p1, Constant_expression p2) { ident_ = p1; constant_expression_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof EnumInit) {
      EnumInit x = (EnumInit)o;
      return this.ident_.equals(x.ident_) && this.constant_expression_.equals(x.constant_expression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.constant_expression_.hashCode();
  }


}
