// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Eoctallong  extends Constant {
  public final String octallong_;
  public Eoctallong(String p1) { octallong_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Eoctallong) {
      Eoctallong x = (Eoctallong)o;
      return this.octallong_.equals(x.octallong_);
    }
    return false;
  }

  public int hashCode() {
    return this.octallong_.hashCode();
  }


}
