// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Eoctalunslong  extends Constant {
  public final String octalunslong_;
  public Eoctalunslong(String p1) { octalunslong_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Eoctalunslong) {
      Eoctalunslong x = (Eoctalunslong)o;
      return this.octalunslong_.equals(x.octalunslong_);
    }
    return false;
  }

  public int hashCode() {
    return this.octalunslong_.hashCode();
  }


}
