// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Epoint  extends Exp {
  public final Exp exp_;
  public final String ident_;
  public Epoint(Exp p1, String p2) { exp_ = p1; ident_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Epoint) {
      Epoint x = (Epoint)o;
      return this.exp_.equals(x.exp_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.ident_.hashCode();
  }


}
