// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

import c.InternalTypeRepresentation;

public class Etimes  extends Exp {
  public final Exp exp_1, exp_2;
  public Etimes(Exp p1, Exp p2, InternalTypeRepresentation type) { super(type);exp_1 = p1; exp_2 = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Etimes) {
      Etimes x = (Etimes)o;
      return this.exp_1.equals(x.exp_1) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_1.hashCode())+this.exp_2.hashCode();
  }


}
