// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Etypeconv  extends Exp {
  public final Type_name type_name_;
  public final Exp exp_;
  public Etypeconv(Type_name p1, Exp p2) { type_name_ = p1; exp_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Etypeconv) {
      Etypeconv x = (Etypeconv)o;
      return this.type_name_.equals(x.type_name_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_name_.hashCode())+this.exp_.hashCode();
  }


}
