// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

import c.InternalTypeRepresentation;

public abstract class Exp implements java.io.Serializable {
  public InternalTypeRepresentation type;
  public Exp(InternalTypeRepresentation type) {this.type = type;}
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Ecomma p, A arg);
    public R visit(Eassign p, A arg);
    public R visit(Econdition p, A arg);
    public R visit(Elor p, A arg);
    public R visit(Eland p, A arg);
    public R visit(Ebitor p, A arg);
    public R visit(Ebitexor p, A arg);
    public R visit(Ebitand p, A arg);
    public R visit(Eeq p, A arg);
    public R visit(Eneq p, A arg);
    public R visit(Elthen p, A arg);
    public R visit(Egrthen p, A arg);
    public R visit(Ele p, A arg);
    public R visit(Ege p, A arg);
    public R visit(Eleft p, A arg);
    public R visit(Eright p, A arg);
    public R visit(Eplus p, A arg);
    public R visit(Eminus p, A arg);
    public R visit(Etimes p, A arg);
    public R visit(Ediv p, A arg);
    public R visit(Emod p, A arg);
    public R visit(Etypeconv p, A arg);
    public R visit(Epreinc p, A arg);
    public R visit(Epredec p, A arg);
    public R visit(Epreop p, A arg);
    public R visit(Ebytesexpr p, A arg);
    public R visit(Ebytestype p, A arg);
    public R visit(Earray p, A arg);
    public R visit(Efunk p, A arg);
    public R visit(Efunkpar p, A arg);
    public R visit(Eselect p, A arg);
    public R visit(Epoint p, A arg);
    public R visit(Epostinc p, A arg);
    public R visit(Epostdec p, A arg);
    public R visit(Evar p, A arg);
    public R visit(Econst p, A arg);
    public R visit(Estring p, A arg);
  }
}
