// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Field  extends Struct_declarator {
  public final Constant_expression constant_expression_;
  public Field(Constant_expression p1) { constant_expression_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Field) {
      Field x = (Field)o;
      return this.constant_expression_.equals(x.constant_expression_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_expression_.hashCode();
  }


}
