// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Global  extends External_declaration {
  public final Dec dec_;
  public Global(Dec p1) { dec_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Global) {
      Global x = (Global)o;
      return this.dec_.equals(x.dec_);
    }
    return false;
  }

  public int hashCode() {
    return this.dec_.hashCode();
  }


}
