// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Incomplete  extends Direct_declarator {
  public final Direct_declarator direct_declarator_;
  public Incomplete(Direct_declarator p1) { direct_declarator_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Incomplete) {
      Incomplete x = (Incomplete)o;
      return this.direct_declarator_.equals(x.direct_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return this.direct_declarator_.hashCode();
  }


}
