// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class InitListOne  extends Initializer {
  public final Initializers initializers_;
  public InitListOne(Initializers p1) { initializers_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof InitListOne) {
      InitListOne x = (InitListOne)o;
      return this.initializers_.equals(x.initializers_);
    }
    return false;
  }

  public int hashCode() {
    return this.initializers_.hashCode();
  }


}
