// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Init_declarator implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(OnlyDecl p, A arg);
    public R visit(InitDecl p, A arg);

  }

}
