// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Initializers implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(AnInit p, A arg);
    public R visit(MoreInit p, A arg);

  }

}
