// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class InnitArray  extends Direct_declarator {
  public final Direct_declarator direct_declarator_;
  public final Constant_expression constant_expression_;
  public InnitArray(Direct_declarator p1, Constant_expression p2) { direct_declarator_ = p1; constant_expression_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof InnitArray) {
      InnitArray x = (InnitArray)o;
      return this.direct_declarator_.equals(x.direct_declarator_) && this.constant_expression_.equals(x.constant_expression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.direct_declarator_.hashCode())+this.constant_expression_.hashCode();
  }


}
