// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class IterS  extends Stm {
  public final Iter_stm iter_stm_;
  public IterS(Iter_stm p1) { iter_stm_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof IterS) {
      IterS x = (IterS)o;
      return this.iter_stm_.equals(x.iter_stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.iter_stm_.hashCode();
  }


}
