// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Iter_stm implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(SiterOne p, A arg);
    public R visit(SiterTwo p, A arg);
    public R visit(SiterThree p, A arg);
    public R visit(SiterFour p, A arg);

  }

}
