// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class JumpS  extends Stm {
  public final Jump_stm jump_stm_;
  public JumpS(Jump_stm p1) { jump_stm_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof JumpS) {
      JumpS x = (JumpS)o;
      return this.jump_stm_.equals(x.jump_stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.jump_stm_.hashCode();
  }


}
