// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Jump_stm implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(SjumpOne p, A arg);
    public R visit(SjumpTwo p, A arg);
    public R visit(SjumpThree p, A arg);
    public R visit(SjumpFour p, A arg);
    public R visit(SjumpFive p, A arg);

  }

}
