// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class MoreParamDec  extends Parameter_declarations {
  public final Parameter_declarations parameter_declarations_;
  public final Parameter_declaration parameter_declaration_;
  public MoreParamDec(Parameter_declarations p1, Parameter_declaration p2) { parameter_declarations_ = p1; parameter_declaration_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof MoreParamDec) {
      MoreParamDec x = (MoreParamDec)o;
      return this.parameter_declarations_.equals(x.parameter_declarations_) && this.parameter_declaration_.equals(x.parameter_declaration_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.parameter_declarations_.hashCode())+this.parameter_declaration_.hashCode();
  }


}
