// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class MoreInit  extends Initializers {
  public final Initializers initializers_;
  public final Initializer initializer_;
  public MoreInit(Initializers p1, Initializer p2) { initializers_ = p1; initializer_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof MoreInit) {
      MoreInit x = (MoreInit)o;
      return this.initializers_.equals(x.initializers_) && this.initializer_.equals(x.initializer_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.initializers_.hashCode())+this.initializer_.hashCode();
  }


}
