// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class NewFunction  extends Dir_abs_dec {
  public final Parameter_type parameter_type_;
  public NewFunction(Parameter_type p1) { parameter_type_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof NewFunction) {
      NewFunction x = (NewFunction)o;
      return this.parameter_type_.equals(x.parameter_type_);
    }
    return false;
  }

  public int hashCode() {
    return this.parameter_type_.hashCode();
  }


}
