// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class NewFuncDec  extends Direct_declarator {
  public final Direct_declarator direct_declarator_;
  public final Parameter_type parameter_type_;
  public NewFuncDec(Direct_declarator p1, Parameter_type p2) { direct_declarator_ = p1; parameter_type_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof NewFuncDec) {
      NewFuncDec x = (NewFuncDec)o;
      return this.direct_declarator_.equals(x.direct_declarator_) && this.parameter_type_.equals(x.parameter_type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.direct_declarator_.hashCode())+this.parameter_type_.hashCode();
  }


}
