// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class NoDeclarator  extends Dec {
  public final ListDeclaration_specifier listdeclaration_specifier_;
  public NoDeclarator(ListDeclaration_specifier p1) { listdeclaration_specifier_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof NoDeclarator) {
      NoDeclarator x = (NoDeclarator)o;
      return this.listdeclaration_specifier_.equals(x.listdeclaration_specifier_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdeclaration_specifier_.hashCode();
  }


}
