// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class OldFunc  extends Function_def {
  public final ListDeclaration_specifier listdeclaration_specifier_;
  public final Declarator declarator_;
  public final ListDec listdec_;
  public final Compound_stm compound_stm_;
  public OldFunc(ListDeclaration_specifier p1, Declarator p2, ListDec p3, Compound_stm p4) { listdeclaration_specifier_ = p1; declarator_ = p2; listdec_ = p3; compound_stm_ = p4; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof OldFunc) {
      OldFunc x = (OldFunc)o;
      return this.listdeclaration_specifier_.equals(x.listdeclaration_specifier_) && this.declarator_.equals(x.declarator_) && this.listdec_.equals(x.listdec_) && this.compound_stm_.equals(x.compound_stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.listdeclaration_specifier_.hashCode())+this.declarator_.hashCode())+this.listdec_.hashCode())+this.compound_stm_.hashCode();
  }


}
