// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class OldFuncExpr  extends Dir_abs_dec {
  public final Dir_abs_dec dir_abs_dec_;
  public OldFuncExpr(Dir_abs_dec p1) { dir_abs_dec_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof OldFuncExpr) {
      OldFuncExpr x = (OldFuncExpr)o;
      return this.dir_abs_dec_.equals(x.dir_abs_dec_);
    }
    return false;
  }

  public int hashCode() {
    return this.dir_abs_dec_.hashCode();
  }


}
