// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class ParamDec  extends Parameter_declarations {
  public final Parameter_declaration parameter_declaration_;
  public ParamDec(Parameter_declaration p1) { parameter_declaration_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof ParamDec) {
      ParamDec x = (ParamDec)o;
      return this.parameter_declaration_.equals(x.parameter_declaration_);
    }
    return false;
  }

  public int hashCode() {
    return this.parameter_declaration_.hashCode();
  }


}
