// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Parameter_type implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(AllSpec p, A arg);
    public R visit(More p, A arg);

  }

}
