// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Parameter_declaration implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(OnlyType p, A arg);
    public R visit(TypeAndParam p, A arg);
    public R visit(Abstract p, A arg);

  }

}
