// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class PointerStart  extends Abstract_declarator {
  public final Pointer pointer_;
  public PointerStart(Pointer p1) { pointer_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof PointerStart) {
      PointerStart x = (PointerStart)o;
      return this.pointer_.equals(x.pointer_);
    }
    return false;
  }

  public int hashCode() {
    return this.pointer_.hashCode();
  }


}
