// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Pointer implements java.io.Serializable {
  int nrOfPointers;
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Point p, A arg);
    public R visit(PointQual p, A arg);
    public R visit(PointPoint p, A arg);
    public R visit(PointQualPoint p, A arg);

  }

}
