// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Progr  extends Program {
  public final ListExternal_declaration listexternal_declaration_;
  public Progr(ListExternal_declaration p1) { listexternal_declaration_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Progr) {
      Progr x = (Progr)o;
      return this.listexternal_declaration_.equals(x.listexternal_declaration_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexternal_declaration_.hashCode();
  }


}
