// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class ScompThree  extends Compound_stm {
  public final ListDec listdec_;
  public ScompThree(ListDec p1) { listdec_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof ScompThree) {
      ScompThree x = (ScompThree)o;
      return this.listdec_.equals(x.listdec_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdec_.hashCode();
  }


}
