// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Selection_stm implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(SselOne p, A arg);
    public R visit(SselTwo p, A arg);
    public R visit(SselThree p, A arg);

  }

}
