// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class SelS  extends Stm {
  public final Selection_stm selection_stm_;
  public SelS(Selection_stm p1) { selection_stm_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof SelS) {
      SelS x = (SelS)o;
      return this.selection_stm_.equals(x.selection_stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.selection_stm_.hashCode();
  }


}
