// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class SlabelTwo  extends Labeled_stm {
  public final Constant_expression constant_expression_;
  public final Stm stm_;
  public SlabelTwo(Constant_expression p1, Stm p2) { constant_expression_ = p1; stm_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof SlabelTwo) {
      SlabelTwo x = (SlabelTwo)o;
      return this.constant_expression_.equals(x.constant_expression_) && this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.constant_expression_.hashCode())+this.stm_.hashCode();
  }


}
