// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class SlabelThree  extends Labeled_stm {
  public final Stm stm_;
  public SlabelThree(Stm p1) { stm_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof SlabelThree) {
      SlabelThree x = (SlabelThree)o;
      return this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_.hashCode();
  }


}
