// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class SpecProp  extends Declaration_specifier {
  public final Type_qualifier type_qualifier_;
  public SpecProp(Type_qualifier p1) { type_qualifier_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof SpecProp) {
      SpecProp x = (SpecProp)o;
      return this.type_qualifier_.equals(x.type_qualifier_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_qualifier_.hashCode();
  }


}
