// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class SselThree  extends Selection_stm {
  public final Exp exp_;
  public final Stm stm_;
  public SselThree(Exp p1, Stm p2) { exp_ = p1; stm_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof SselThree) {
      SselThree x = (SselThree)o;
      return this.exp_.equals(x.exp_) && this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.stm_.hashCode();
  }


}
