// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Storage_class_specifier implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(MyType p, A arg);
    public R visit(GlobalPrograms p, A arg);
    public R visit(LocalProgram p, A arg);
    public R visit(LocalBlock p, A arg);
    public R visit(LocalReg p, A arg);

  }

}
