// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Storage  extends Declaration_specifier {
  public final Storage_class_specifier storage_class_specifier_;
  public Storage(Storage_class_specifier p1) { storage_class_specifier_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Storage) {
      Storage x = (Storage)o;
      return this.storage_class_specifier_.equals(x.storage_class_specifier_);
    }
    return false;
  }

  public int hashCode() {
    return this.storage_class_specifier_.hashCode();
  }


}
