// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Struct_declarator implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Decl p, A arg);
    public R visit(Field p, A arg);
    public R visit(DecField p, A arg);

  }

}
