// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Struct_or_union_spec implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Tag p, A arg);
    public R visit(Unique p, A arg);
    public R visit(TagType p, A arg);

  }

}
