// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class Type  extends Declaration_specifier {
  public final Type_specifier type_specifier_;
  public Type(Type_specifier p1) { type_specifier_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Type) {
      Type x = (Type)o;
      return this.type_specifier_.equals(x.type_specifier_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_specifier_.hashCode();
  }


}
