// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class TypeAndParam  extends Parameter_declaration {
  public final ListDeclaration_specifier listdeclaration_specifier_;
  public final Declarator declarator_;
  public TypeAndParam(ListDeclaration_specifier p1, Declarator p2) { listdeclaration_specifier_ = p1; declarator_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof TypeAndParam) {
      TypeAndParam x = (TypeAndParam)o;
      return this.listdeclaration_specifier_.equals(x.listdeclaration_specifier_) && this.declarator_.equals(x.declarator_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listdeclaration_specifier_.hashCode())+this.declarator_.hashCode();
  }


}
