// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

import c.InternalTypeRepresentation;

public abstract class Type_name implements java.io.Serializable {
  public InternalTypeRepresentation type;
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(PlainType p, A arg);
    public R visit(ExtendedType p, A arg);

  }

}
