// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public abstract class Unary_operator implements java.io.Serializable {
  public abstract <R,A> R accept(Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Address p, A arg);
    public R visit(Indirection p, A arg);
    public R visit(Plus p, A arg);
    public R visit(Negative p, A arg);
    public R visit(Complement p, A arg);
    public R visit(Logicalneg p, A arg);

  }

}
