// File generated by the BNF Converter (bnfc 2.9.5).

package c.Typedsyn;

public class WithinParentes  extends Dir_abs_dec {
  public final Abstract_declarator abstract_declarator_;
  public WithinParentes(Abstract_declarator p1) { abstract_declarator_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof WithinParentes) {
      WithinParentes x = (WithinParentes)o;
      return this.abstract_declarator_.equals(x.abstract_declarator_);
    }
    return false;
  }

  public int hashCode() {
    return this.abstract_declarator_.hashCode();
  }


}
